// Command proxysrc packages the sidecar's source into the engine binary.
//
// The sidecar has to run inside the environment, which means it has to be a
// container image, which means something has to compile it. Pulling a
// published image would be the obvious answer and is the wrong one right now:
// there is no release yet, and an air gapped user should not need one.
//
// So the engine carries the sidecar's source and builds the image itself. The
// alternative, writing the proxy as a standalone program with its own copy of
// the matching logic, would put two implementations of a security control in
// one repository, and the one that drifted would be the one deciding real
// traffic. This keeps exactly one.
//
// The generated file is checked in and a test asserts it is current, which is
// the same arrangement the error catalog uses.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// sources are the files the sidecar's image needs, relative to engine/.
//
// The set is small on purpose. policy and schema import nothing outside the
// standard library, so the build inside the image downloads no modules and
// works with no network, and adding a dependency to either of them would
// break that loudly here rather than quietly at somebody's first af up.
var sources = []string{
	"pkg/schema/manifest.go",
	"internal/policy/policy.go",
	"cmd/af-proxy/main.go",
	"cmd/af-proxy/dns.go",
	"cmd/af-proxy/transparent.go",
	"cmd/af-proxy/mitm.go",
}

// modulePath is the module the generated files declare.
const modulePath = "github.com/antifailure/antifailure/engine"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "proxysrc:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := engineRoot()
	if err != nil {
		return err
	}
	body, err := Generate(root)
	if err != nil {
		return err
	}
	out := filepath.Join(root, "internal", "proxyimage", "sources.gen.go")
	if err := os.WriteFile(out, body, 0o644); err != nil {
		return err
	}
	fmt.Printf("proxysrc: %d files packaged\n", len(sources))
	return nil
}

// Generate returns the content of the generated file.
//
// Exported so the test can call it and compare, rather than shelling out to
// this program and comparing what it wrote.
func Generate(engineDir string) ([]byte, error) {
	files := map[string]string{}
	for _, rel := range sources {
		body, err := os.ReadFile(filepath.Join(engineDir, filepath.FromSlash(rel)))
		if err != nil {
			return nil, err
		}
		files[rel] = string(body)
	}
	// A module file with no requirements, which is what makes the build inside
	// the image work with no network access.
	files["go.mod"] = "module " + modulePath + "\n\ngo 1.25.0\n"

	names := make([]string, 0, len(files))
	for n := range files {
		names = append(names, n)
	}
	sort.Strings(names)

	var b bytes.Buffer
	b.WriteString("// Code generated by tools/proxysrc. DO NOT EDIT.\n\n")
	b.WriteString("package proxyimage\n\n")
	b.WriteString("// Sources is the sidecar's build context, keyed by path.\n")
	b.WriteString("//\n")
	b.WriteString("// It is generated from the real packages rather than written here, so that\n")
	b.WriteString("// the proxy deciding live traffic and the command line explaining a decision\n")
	b.WriteString("// run the same code.\n")
	b.WriteString("var Sources = map[string]string{\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\t%s: %s,\n", strconv.Quote(n), backquote(files[n]))
	}
	b.WriteString("}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting the generated file: %w", err)
	}
	return formatted, nil
}

// backquote renders a string as a Go literal.
//
// A raw literal keeps the source readable in the generated file, which matters
// because somebody auditing what runs inside their environment should be able
// to read it here. Source containing a backquote falls back to a quoted
// literal rather than producing something that does not compile.
func backquote(s string) string {
	if !strings.Contains(s, "`") && !strings.Contains(s, "\r") {
		return "`" + s + "`"
	}
	return strconv.Quote(s)
}

// engineRoot finds the engine directory from the working directory.
func engineRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for _, candidate := range []string{
		filepath.Join(wd, "engine"),
		wd,
		filepath.Join(wd, ".."),
		filepath.Join(wd, "..", "engine"),
	} {
		if _, err := os.Stat(filepath.Join(candidate, "go.mod")); err == nil {
			abs, absErr := filepath.Abs(candidate)
			if absErr != nil {
				return "", absErr
			}
			return abs, nil
		}
	}
	return "", fmt.Errorf("no engine directory with a go.mod was found from %s", wd)
}
