// Command docsembed packages the documentation site's pages into the engine
// binary.
//
// The engine's MCP server answers questions about this product to an agent
// that has never seen it. No model has Antifailure in its training data, so an
// agent handed the server can submit rehearsals and read verdicts while having
// no way to find out what a stance is, what topology measures, or why a golden
// that fails verification cannot be branched. It guesses, and it guesses
// confidently, because nothing tells it otherwise.
//
// The answer has to be the documentation that SHIPS, for the same reason the
// sidecar carries its own source rather than pulling a published image: an
// agent is running one build of the engine and the answer has to match that
// build. Fetching antifailure.dev would answer about whatever is deployed
// today, which is a different product from the one in the caller's hands the
// moment a release is a week old, and it would need a network from a tool
// whose whole value is being available with none.
//
// Embedding rather than reading from disk, and this is the part that is easy
// to get backwards. The server is bound to the CALLER'S checkout, which is
// their application and not this repository. There is no docs/ directory
// under it to read. So the pages travel in the binary.
//
// //go:embed cannot reach outside its own package directory and docs/ is
// outside engine/, so a generated file is the only way to carry them. The
// generated file is checked in, `just generate` writes it, and CI regenerates
// and diffs, which is the arrangement the error catalog and the sidecar's
// sources already use.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// contentDir is where the documentation site keeps its pages, relative to the
// repository root. It is the directory Astro renders, so a page here is a page
// that ships, and a page that is not here does not exist on the site either.
const contentDir = "docs/src/content/docs"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "docsembed:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := repositoryRoot()
	if err != nil {
		return err
	}
	body, count, err := Generate(root)
	if err != nil {
		return err
	}
	out := filepath.Join(root, "engine", "internal", "docs", "pages.gen.go")
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(out, body, 0o644); err != nil {
		return err
	}
	fmt.Printf("docsembed: %d pages packaged\n", count)
	return nil
}

// Generate returns the content of the generated file and how many pages it
// carries.
//
// Exported so the drift test calls it and compares, rather than shelling out
// to this program and comparing what it wrote.
func Generate(repoRoot string) ([]byte, int, error) {
	dir := filepath.Join(repoRoot, filepath.FromSlash(contentDir))
	pages, err := collect(dir)
	if err != nil {
		return nil, 0, err
	}
	if len(pages) == 0 {
		// A generator that finds nothing would write an empty map, every
		// documentation tool would answer "no page matched" to every question,
		// and every test that asks whether a search can come back empty would
		// pass. Refusing is the only honest outcome.
		return nil, 0, fmt.Errorf("no Markdown page was found under %s", contentDir)
	}

	names := make([]string, 0, len(pages))
	for name := range pages {
		names = append(names, name)
	}
	sort.Strings(names)

	var b bytes.Buffer
	b.WriteString("// Code generated by tools/docsembed. DO NOT EDIT.\n\n")
	b.WriteString("package docs\n\n")
	b.WriteString("// Pages is the documentation this build ships, keyed by the page's path\n")
	b.WriteString("// under " + contentDir + ".\n")
	b.WriteString("//\n")
	b.WriteString("// It is generated from the site's own content rather than written here, so\n")
	b.WriteString("// that the answer an agent reads over MCP is the documentation for the\n")
	b.WriteString("// build it is talking to rather than whatever is on the website today.\n")
	b.WriteString("var Pages = map[string]string{\n")
	for _, n := range names {
		literal, litErr := goLiteral(pages[n])
		if litErr != nil {
			return nil, 0, fmt.Errorf("%s: %w", n, litErr)
		}
		fmt.Fprintf(&b, "\t%s: %s,\n", strconv.Quote(n), literal)
	}
	b.WriteString("}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, 0, fmt.Errorf("formatting the generated file: %w", err)
	}
	return formatted, len(pages), nil
}

// collect reads every Markdown page under dir, keyed by its slash separated
// path relative to dir.
func collect(dir string) (map[string]string, error) {
	pages := map[string]string{}
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(d.Name(), ".md") {
			return nil
		}
		rel, relErr := filepath.Rel(dir, path)
		if relErr != nil {
			return relErr
		}
		body, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		pages[filepath.ToSlash(rel)] = string(body)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return pages, nil
}

// goLiteral renders one page as a Go string literal that stays readable in a
// diff.
//
// tools/proxysrc falls back to strconv.Quote for a file containing a
// backquote, which puts the whole file on ONE line. That is tolerable for nine
// source files nobody edits weekly and intolerable here: Markdown is full of
// backticks, so every page would be a single line tens of kilobytes long, and
// a one word documentation fix would show up in review as an unreadable
// regenerated blob. Nobody reviews that, which means nobody would notice the
// day it carried something else.
//
// So a page is split on the backquote and rejoined, and the raw chunks keep
// their newlines. A documentation diff stays a line diff.
func goLiteral(s string) (string, error) {
	if strings.ContainsRune(s, '\r') {
		// A raw literal cannot carry a carriage return, and rewriting the
		// bytes here would make the packaged page differ from the one on disk
		// while every drift check compared the rewritten copy against itself.
		return "", fmt.Errorf(
			"the page contains a carriage return, which cannot be packaged; save it with " +
				"Unix line endings")
	}
	if strings.ContainsRune(s, 0) {
		return "", fmt.Errorf("the page contains a NUL byte, which is not text")
	}
	parts := strings.Split(s, "`")
	quoted := make([]string, 0, len(parts)*2)
	for i, part := range parts {
		if i > 0 {
			quoted = append(quoted, `"`+"`"+`"`)
		}
		if part == "" {
			// An empty raw chunk between two adjacent backquotes would add
			// `` + to the expression and say nothing.
			continue
		}
		quoted = append(quoted, "`"+part+"`")
	}
	if len(quoted) == 0 {
		return `""`, nil
	}
	return strings.Join(quoted, " + "), nil
}

// repositoryRoot finds the repository from the working directory.
//
// The same shape as tools/proxysrc's engineRoot, looking for the content
// directory rather than for a go.mod, because that is the thing this command
// needs and a repository without it cannot be packaged from at all.
func repositoryRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for _, candidate := range []string{wd, filepath.Join(wd, ".."), filepath.Join(wd, "..", "..")} {
		if _, err := os.Stat(filepath.Join(candidate, filepath.FromSlash(contentDir))); err == nil {
			return filepath.Abs(candidate)
		}
	}
	return "", fmt.Errorf("no %s was found from %s", contentDir, wd)
}
