// Code generated by tools/errgen from catalog.yaml. DO NOT EDIT.

package errors

// Catalog codes. Each constant names an entry in catalog.yaml.
const (
	// Agents
	// The agent runner could not be started: {detail}
	AFAGT001 Code = "AF-AGT-001"
	// Workflow {workflow} exhausted its budget of {budget} before
	// completing.
	AFAGT002 Code = "AF-AGT-002"
	// The agent runner produced no readable output: {detail}
	AFAGT003 Code = "AF-AGT-003"
	// The agent runner could not be found: {detail}
	AFAGT004 Code = "AF-AGT-004"
	// The {provider} key was not accepted: {detail}
	AFAGT005 Code = "AF-AGT-005"
	// The {provider} endpoint could not be reached: {detail}
	AFAGT006 Code = "AF-AGT-006"
	// Invariant {invariant} did not finish within {timeout}.
	AFAGT010 Code = "AF-AGT-010"
	// Invariant {invariant} is not read only.
	AFAGT011 Code = "AF-AGT-011"
	// Invariant {invariant} does not hold: {detail}
	AFAGT012 Code = "AF-AGT-012"
	// There is nothing to explore: {detail}
	AFAGT020 Code = "AF-AGT-020"
	// No goal named {goal} is declared under explore.
	AFAGT021 Code = "AF-AGT-021"

	// Build
	// The build for service {service} failed after {duration}.
	AFBLD001 Code = "AF-BLD-001"
	// The Dockerfile for {service} is not valid at line {line}: {detail}
	AFBLD002 Code = "AF-BLD-002"
	// The build context for {service} is {size}, above the {limit} limit.
	AFBLD003 Code = "AF-BLD-003"
	// The build context for {service} holds more than {count} files;
	// {path} is where the count was reached.
	AFBLD004 Code = "AF-BLD-004"
	// The build for service {service} failed after {duration}, and its
	// Dockerfile is {dockerfile} inside a build context rooted at the
	// repository.
	AFBLD005 Code = "AF-BLD-005"
	// No build strategy could be detected for {service}.
	AFBLD010 Code = "AF-BLD-010"
	// The Dockerfile {dockerfile} for {service} is excluded from the build
	// context by .dockerignore.
	AFBLD011 Code = "AF-BLD-011"
	// The Dockerfile {dockerfile} for {service} is outside the build
	// context {context}.
	AFBLD012 Code = "AF-BLD-012"

	// Control plane
	// The control plane at {url} could not be reached.
	AFCP001 Code = "AF-CP-001"
	// The control plane rejected this engine's token.
	AFCP002 Code = "AF-CP-002"

	// Control plane
	// No control plane token is configured.
	AFCPL001 Code = "AF-CPL-001"
	// The control plane has no environment called {env}.
	AFCPL002 Code = "AF-CPL-002"
	// The control plane could not be reached: {detail}
	AFCPL003 Code = "AF-CPL-003"
	// This machine is not signed in to {origin}.
	AFCPL004 Code = "AF-CPL-004"

	// Database
	// The database provider {provider} is not registered in this build.
	AFDB001 Code = "AF-DB-001"
	// The source database at {host} could not be reached.
	AFDB002 Code = "AF-DB-002"
	// The source database is Postgres {found}, and this provider supports
	// {supported}.
	AFDB003 Code = "AF-DB-003"
	// The golden version {version} no longer exists.
	AFDB004 Code = "AF-DB-004"
	// The golden version {version} is still referenced by {count}
	// environments and cannot be collected.
	AFDB005 Code = "AF-DB-005"
	// The provider's concurrent branch limit ({limit}) is reached.
	AFDB006 Code = "AF-DB-006"
	// Extension {extension} is required by the golden and is not available
	// on the target.
	AFDB007 Code = "AF-DB-007"
	// The database provider {provider} at {endpoint} rejected the
	// configured credential.
	AFDB008 Code = "AF-DB-008"
	// The Database Lab Engine at {endpoint} has no snapshot to build a
	// golden from: {detail}
	AFDB009 Code = "AF-DB-009"
	// The storage pool has {available} free and the operation needs
	// {needed}.
	AFDB010 Code = "AF-DB-010"
	// The subset could not be taken: {detail}
	AFDB011 Code = "AF-DB-011"
	// No golden matches this manifest's masking rules, and {count} were
	// made under different ones.
	AFDB012 Code = "AF-DB-012"
	// The database seed command failed: {detail}
	AFDB013 Code = "AF-DB-013"
	// No database branch exists for {env}.
	AFDB014 Code = "AF-DB-014"
	// Personas cannot be provisioned because {provider} creates users only
	// through its own API, and no sandbox tenant is configured.
	AFDB020 Code = "AF-DB-020"
	// {provider} rejected the admin token used to create personas.
	AFDB021 Code = "AF-DB-021"
	// Migrations failed on the branch: {detail}
	AFDB030 Code = "AF-DB-030"
	// The migration finding {rule} fails this project's policy: {detail}
	AFDB031 Code = "AF-DB-031"
	// The previous release does not survive this migration: {detail}
	AFDB032 Code = "AF-DB-032"

	// Detection
	// No application could be detected in {path}.
	AFDET001 Code = "AF-DET-001"
	// Detection stopped after {budget} with partial results.
	AFDET002 Code = "AF-DET-002"
	// Detection could not decide {question}, and there is no default to
	// fall back on.
	AFDET004 Code = "AF-DET-004"
	// Detection produced a draft that is not a valid manifest, so nothing
	// was written and {path} does not exist: {detail}
	AFDET005 Code = "AF-DET-005"
	// --answer {id}=... does not name anything in this repository.
	AFDET006 Code = "AF-DET-006"
	// The changed files between {base} and {head} could not be read:
	// {detail}
	AFDET010 Code = "AF-DET-010"
	// The diff at {path} could not be read: {detail}
	AFDET011 Code = "AF-DET-011"

	// Enterprise
	// The enterprise license could not be verified.
	AFEE001 Code = "AF-EE-001"
	// The system clock is {skew} behind the last time this license was
	// seen.
	AFEE002 Code = "AF-EE-002"
	// This license was issued for organization {issued_for} and this
	// instance is {actual}.
	AFEE003 Code = "AF-EE-003"
	// The license covers {seats} seats and they are all in use.
	AFEE004 Code = "AF-EE-004"
	// Organization policy {policy} refuses this environment: {detail}
	AFEE010 Code = "AF-EE-010"

	// Fidelity
	// The environment does not reproduce {dimension}, which the manifest
	// requires: {detail}
	AFFID001 Code = "AF-FID-001"
	// {dimension} is required and could not be measured, so it is neither
	// met nor broken: {detail}
	AFFID002 Code = "AF-FID-002"

	// GitHub
	// The webhook signature did not verify.
	AFGH001 Code = "AF-GH-001"
	// The GitHub API rejected the request: {detail}
	AFGH002 Code = "AF-GH-002"

	// Infrastructure
	// The cloud API returned a quota error for {quota} in {region}.
	AFINF001 Code = "AF-INF-001"
	// The provider rate limited this operation and asked to wait
	// {retry_after}.
	AFINF002 Code = "AF-INF-002"

	// Load
	// The load target {target} is not an environment this engine created.
	AFLOD001 Code = "AF-LOD-001"
	// The load run was aborted after the error rate exceeded {threshold}
	// for {duration}.
	AFLOD002 Code = "AF-LOD-002"
	// Load could not be generated: {detail}
	AFLOD010 Code = "AF-LOD-010"
	// Load exceeded {count} thresholds the manifest sets.
	AFLOD011 Code = "AF-LOD-011"
	// There is no load source called {source}.
	AFLOD012 Code = "AF-LOD-012"
	// The scenario at {path} could not be read: {detail}
	AFLOD013 Code = "AF-LOD-013"
	// {count} scenario assertions did not hold.
	AFLOD014 Code = "AF-LOD-014"
	// The scenario {scenario} proved nothing: {detail}
	AFLOD015 Code = "AF-LOD-015"
	// The p95_increase threshold proved nothing: {detail}
	AFLOD016 Code = "AF-LOD-016"

	// Manifest
	// No antifailure.yaml was found in {path} or any parent directory.
	AFMAN001 Code = "AF-MAN-001"
	// The manifest at {path} is not valid: {detail}
	AFMAN002 Code = "AF-MAN-002"
	// The manifest at {path} declares schema version {found}, which this
	// build does not understand.
	AFMAN003 Code = "AF-MAN-003"
	// 'af init' has questions to ask and this session has no terminal to
	// ask them on.
	AFMAN004 Code = "AF-MAN-004"
	// The manifest at {path} is larger than the {limit} limit.
	AFMAN005 Code = "AF-MAN-005"
	// The path {path} in the manifest resolves outside the repository.
	AFMAN006 Code = "AF-MAN-006"

	// Masking and verification
	// The golden {version} has no valid verification attestation and
	// cannot be branched.
	AFMSK001 Code = "AF-MSK-001"
	// Verification found data matching {detector} in {table}.{column}.
	AFMSK002 Code = "AF-MSK-002"
	// The masking rule for {table}.{column} names a column that does not
	// exist in the schema.
	AFMSK003 Code = "AF-MSK-003"
	// Masking would violate the check constraint {constraint} on
	// {table}.{column}.
	AFMSK004 Code = "AF-MSK-004"
	// Masking is only permitted on a golden candidate, and {target} is a
	// source database.
	AFMSK005 Code = "AF-MSK-005"
	// The transform on {table}.{column} produced duplicate values under
	// the unique constraint {constraint}.
	AFMSK007 Code = "AF-MSK-007"
	// The columns {columns} hold free text and have no masking rule.
	AFMSK008 Code = "AF-MSK-008"
	// Masking could not run: {detail}
	AFMSK010 Code = "AF-MSK-010"

	// Egress
	// The request to {host} was blocked by rule {rule}.
	AFNET001 Code = "AF-NET-001"
	// {request} is not a request that can be explained: {detail}
	AFNET002 Code = "AF-NET-002"
	// A request to {host} carried a live credential in the {header} header
	// and was blocked.
	AFNET004 Code = "AF-NET-004"
	// The sandbox credential for {host} was rejected: {detail}
	AFNET005 Code = "AF-NET-005"
	// No mock matched {method} {path} on {host}.
	AFNET010 Code = "AF-NET-010"
	// No message matching {match} arrived within {timeout}.
	AFNET011 Code = "AF-NET-011"
	// The webhook could not be delivered to {service}: {detail}
	AFNET012 Code = "AF-NET-012"
	// The environment tried to reach {hosts}, which nothing in the
	// manifest mentions.
	AFNET013 Code = "AF-NET-013"
	// {host} rejected the environment certificate, which usually means the
	// client pins its own.
	AFNET020 Code = "AF-NET-020"
	// {host} resolves only to IPv6 and the environment has IPv6 disabled.
	AFNET021 Code = "AF-NET-021"
	// The synthesis model returned no usable response for {method} {path}.
	AFNET030 Code = "AF-NET-030"

	// Differential oracle
	// The manifest declares no oracle block, so there is nothing to
	// compare.
	AFORC001 Code = "AF-ORC-001"
	// The oracle is on and declares no requests to send.
	AFORC002 Code = "AF-ORC-002"
	// The baseline revision could not be resolved: {detail}
	AFORC003 Code = "AF-ORC-003"
	// The baseline and the candidate are both {commit}, so there is
	// nothing to compare.
	AFORC004 Code = "AF-ORC-004"
	// The baseline revision {commit} could not be checked out: {detail}
	AFORC005 Code = "AF-ORC-005"
	// There is no web service to send requests to in the {side}
	// environment.
	AFORC006 Code = "AF-ORC-006"
	// The baseline environment did not come up: {detail}
	AFORC007 Code = "AF-ORC-007"
	// The {side} branch could not be read for comparison: {detail}
	AFORC008 Code = "AF-ORC-008"
	// The golden version {version} the comparison pinned is no longer
	// present or no longer verified.
	AFORC009 Code = "AF-ORC-009"
	// The candidate behaves differently from the baseline: {detail}
	AFORC010 Code = "AF-ORC-010"

	// Runtime
	// The command '{command}' is not available in this version.
	AFRUN001 Code = "AF-RUN-001"
	// The Docker daemon at {endpoint} could not be reached.
	AFRUN002 Code = "AF-RUN-002"
	// Another Antifailure process holds the lock for this branch (process
	// {pid}, since {since}).
	AFRUN003 Code = "AF-RUN-003"
	// Service {service} did not become ready within {timeout}.
	AFRUN004 Code = "AF-RUN-004"
	// Service {service} exited with code {code} during startup.
	AFRUN005 Code = "AF-RUN-005"
	// No free port was found in the range {range} to publish the
	// environment on.
	AFRUN009 Code = "AF-RUN-009"
	// Writing to {path} failed because the disk is full; {needed} is
	// required.
	AFRUN010 Code = "AF-RUN-010"
	// The local state database at {path} is corrupt.
	AFRUN011 Code = "AF-RUN-011"
	// Docker has no room left for the environment: {detail}
	AFRUN020 Code = "AF-RUN-020"
	// The environment could not be torn down completely; {count} resources
	// are still recorded.
	AFRUN030 Code = "AF-RUN-030"
	// The environment could not be placed: {detail}
	AFRUN040 Code = "AF-RUN-040"
	// The services depend on each other in a cycle: {cycle}
	AFRUN041 Code = "AF-RUN-041"
	// Service {service} depends on {missing}, which the manifest does not
	// declare.
	AFRUN042 Code = "AF-RUN-042"
	// This cluster is not containing the environment: {detail}
	AFRUN043 Code = "AF-RUN-043"
	// This runtime cannot do that: {detail}
	AFRUN044 Code = "AF-RUN-044"
	// {kind} {name} was not created by this runtime, so it was not
	// removed.
	AFRUN045 Code = "AF-RUN-045"
	// AF_PORT_RANGE_START is set to {value}, which is not a port number.
	AFRUN046 Code = "AF-RUN-046"

	// Scheduling
	// No runtime satisfies the placement requirement {requirement}.
	AFSCH001 Code = "AF-SCH-001"
	// The organization is at its concurrent environment limit ({limit});
	// this run is queued at position {position}.
	AFSCH002 Code = "AF-SCH-002"

	// Secrets
	// The variables {names} are declared in the manifest but were not
	// found in any configured source.
	AFSEC001 Code = "AF-SEC-001"
	// The credential for {source} was rejected after one refresh: {detail}
	AFSEC002 Code = "AF-SEC-002"
	// The value supplied for {name} carries a live credential prefix, and
	// {name} is configured for sandbox use.
	AFSEC003 Code = "AF-SEC-003"
	// The encrypted local store has no passphrase: no system keyring
	// answered and AF_SECRET_PASSPHRASE is not set.
	AFSEC004 Code = "AF-SEC-004"
	// The environment certificate could not be created: {detail}
	AFSEC010 Code = "AF-SEC-010"
)

// catalog is the generated lookup table.
var catalog = map[Code]Entry{
	AFAGT001: {
		Code:      AFAGT001,
		Area:      "AGT",
		Message:   "The agent runner could not be started: {detail}",
		NextStep:  "Run 'af doctor' to check that the runner and its browsers are installed.",
		Docs:      "concepts/agents",
		Retryable: true,
		ExitCode:  ExitFailure,
	},
	AFAGT002: {
		Code:      AFAGT002,
		Area:      "AGT",
		Message:   "Workflow {workflow} exhausted its budget of {budget} before completing.",
		NextStep:  "Raise the budget for {workflow} in the manifest, or split it into smaller workflows.",
		Docs:      "guides/workflows",
		Retryable: false,
		ExitCode:  ExitTestFailure,
	},
	AFAGT003: {
		Code:      AFAGT003,
		Area:      "AGT",
		Message:   "The agent runner produced no readable output: {detail}",
		NextStep:  "This is the runner's own failure and not the application's; the output above is what it printed.",
		Docs:      "concepts/agents",
		Retryable: true,
		ExitCode:  ExitFailure,
	},
	AFAGT004: {
		Code:      AFAGT004,
		Area:      "AGT",
		Message:   "The agent runner could not be found: {detail}",
		NextStep:  "Install it with 'af runner install', or point at a checkout with --runner.",
		Docs:      "concepts/agents",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFAGT005: {
		Code:      AFAGT005,
		Area:      "AGT",
		Message:   "The {provider} key was not accepted: {detail}",
		NextStep:  "{next_step}",
		Docs:      "guides/model-keys",
		Retryable: false,
		ExitCode:  ExitAuth,
	},
	AFAGT006: {
		Code:      AFAGT006,
		Area:      "AGT",
		Message:   "The {provider} endpoint could not be reached: {detail}",
		NextStep:  "{next_step}",
		Docs:      "guides/model-keys",
		Retryable: true,
		ExitCode:  ExitProvider,
	},
	AFAGT010: {
		Code:      AFAGT010,
		Area:      "AGT",
		Message:   "Invariant {invariant} did not finish within {timeout}.",
		NextStep:  "Make the invariant cheaper; it runs after every workflow and must be a quick read.",
		Docs:      "guides/invariants",
		Retryable: false,
		ExitCode:  ExitTestFailure,
	},
	AFAGT011: {
		Code:      AFAGT011,
		Area:      "AGT",
		Message:   "Invariant {invariant} is not read only.",
		NextStep:  "Rewrite it as a single SELECT; invariants run inside a read only transaction.",
		Docs:      "guides/invariants",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFAGT012: {
		Code:      AFAGT012,
		Area:      "AGT",
		Message:   "Invariant {invariant} does not hold: {detail}",
		NextStep:  "The rows the statement returned are the violation. Run it against the branch to see them all.",
		Docs:      "guides/invariants",
		Retryable: false,
		ExitCode:  ExitTestFailure,
	},
	AFAGT020: {
		Code:      AFAGT020,
		Area:      "AGT",
		Message:   "There is nothing to explore: {detail}",
		NextStep:  "Add a goal under explore in the manifest, and set explore.enabled to true.",
		Docs:      "concepts/exploration",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFAGT021: {
		Code:      AFAGT021,
		Area:      "AGT",
		Message:   "No goal named {goal} is declared under explore.",
		NextStep:  "Run 'af explain' to see the goals this manifest declares, then check the spelling.",
		Docs:      "concepts/exploration",
		Retryable: false,
		ExitCode:  ExitUsage,
	},
	AFBLD001: {
		Code:      AFBLD001,
		Area:      "BLD",
		Message:   "The build for service {service} failed after {duration}.",
		NextStep:  "Read the build log above; the first error line names the step that failed.",
		Docs:      "guides/build",
		Retryable: false,
		ExitCode:  ExitFailure,
	},
	AFBLD002: {
		Code:      AFBLD002,
		Area:      "BLD",
		Message:   "The Dockerfile for {service} is not valid at line {line}: {detail}",
		NextStep:  "Fix the line and run 'af up' again.",
		Docs:      "guides/build",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFBLD003: {
		Code:      AFBLD003,
		Area:      "BLD",
		Message:   "The build context for {service} is {size}, above the {limit} limit.",
		NextStep:  "Add large directories to .dockerignore; the build does not need them.",
		Docs:      "guides/build",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFBLD004: {
		Code:      AFBLD004,
		Area:      "BLD",
		Message:   "The build context for {service} holds more than {count} files; {path} is where the count was reached.",
		NextStep:  "Add the generated directories to .dockerignore; a build context should hold source, not output.",
		Docs:      "guides/build",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFBLD005: {
		Code:      AFBLD005,
		Area:      "BLD",
		Message:   "The build for service {service} failed after {duration}, and its Dockerfile is {dockerfile} inside a build context rooted at the repository.",
		NextStep:  "If the Dockerfile expects to be built from its own directory, which is what 'docker build {dir}' does, set build.context to {dir} for this service. Otherwise read the build log above; the first error line names the step that failed.",
		Docs:      "reference/manifest",
		Retryable: false,
		ExitCode:  ExitFailure,
	},
	AFBLD010: {
		Code:      AFBLD010,
		Area:      "BLD",
		Message:   "No build strategy could be detected for {service}.",
		NextStep:  "Add a Dockerfile to {path}, or set services.{service}.build to a strategy the reference lists.",
		Docs:      "guides/build",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFBLD011: {
		Code:      AFBLD011,
		Area:      "BLD",
		Message:   "The Dockerfile {dockerfile} for {service} is excluded from the build context by .dockerignore.",
		NextStep:  "Add '!{dockerfile}' to .dockerignore. The file exists, and the build sends a filtered copy of the tree to the daemon, so a path the ignore file excludes is not there to build from.",
		Docs:      "guides/build",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFBLD012: {
		Code:      AFBLD012,
		Area:      "BLD",
		Message:   "The Dockerfile {dockerfile} for {service} is outside the build context {context}.",
		NextStep:  "Widen build.context, or move the Dockerfile inside it. A build cannot read a file the context does not carry.",
		Docs:      "guides/build",
		Retryable: false,
		ExitCode:  ExitAuth,
	},
	AFCP001: {
		Code:      AFCP001,
		Area:      "CP",
		Message:   "The control plane at {url} could not be reached.",
		NextStep:  "Antifailure works without it. Run af logout, or unset AF_CONTROL_PLANE_URL, to work fully locally.",
		Docs:      "self-hosting/control-plane",
		Retryable: true,
		ExitCode:  ExitProvider,
	},
	AFCP002: {
		Code:      AFCP002,
		Area:      "CP",
		Message:   "The control plane rejected this engine's token.",
		NextStep:  "Run 'af token create ci' and set AF_CONTROL_PLANE_TOKEN to what it prints. The old one was revoked, expired, or belongs to a different control plane.",
		Docs:      "self-hosting/control-plane",
		Retryable: false,
		ExitCode:  ExitAuth,
	},
	AFCPL001: {
		Code:      AFCPL001,
		Area:      "CPL",
		Message:   "No control plane token is configured.",
		NextStep:  "Run 'af login' then 'af token create ci', and set AF_CONTROL_PLANE_TOKEN to what it prints. Everything except this command works without one.",
		Docs:      "self-hosting/control-plane",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFCPL002: {
		Code:      AFCPL002,
		Area:      "CPL",
		Message:   "The control plane has no environment called {env}.",
		NextStep:  "Check the identifier with 'af env list', or confirm the engine that created it was sending events to this control plane.",
		Docs:      "self-hosting/control-plane",
		Retryable: false,
		ExitCode:  ExitAuth,
	},
	AFCPL003: {
		Code:      AFCPL003,
		Area:      "CPL",
		Message:   "The control plane could not be reached: {detail}",
		NextStep:  "Environments keep working without it; events are buffered and sent when it returns. Check AF_CONTROL_PLANE_URL and the network.",
		Docs:      "self-hosting/control-plane",
		Retryable: true,
		ExitCode:  ExitProvider,
	},
	AFCPL004: {
		Code:      AFCPL004,
		Area:      "CPL",
		Message:   "This machine is not signed in to {origin}.",
		NextStep:  "Run '{command}' to sign in from this terminal. Nothing else in the engine needs a sign in; only the commands that read or write your own account do.",
		Docs:      "self-hosting/control-plane",
		Retryable: false,
		ExitCode:  ExitAuth,
	},
	AFDB001: {
		Code:      AFDB001,
		Area:      "DB",
		Message:   "The database provider {provider} is not registered in this build.",
		NextStep:  "Set database.provider to one of: {available}.",
		Docs:      "providers/overview",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFDB002: {
		Code:      AFDB002,
		Area:      "DB",
		Message:   "The source database at {host} could not be reached.",
		NextStep:  "Check that the host is reachable from this machine and that the connection string names the right port.",
		Docs:      "providers/overview",
		Retryable: true,
		ExitCode:  ExitProvider,
	},
	AFDB003: {
		Code:      AFDB003,
		Area:      "DB",
		Message:   "The source database is Postgres {found}, and this provider supports {supported}.",
		NextStep:  "Use a provider that supports Postgres {found}, or upgrade the source.",
		Docs:      "providers/overview",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFDB004: {
		Code:      AFDB004,
		Area:      "DB",
		Message:   "The golden version {version} no longer exists.",
		NextStep:  "Run 'af golden list' to see the available versions, then 'af up --golden <version>'.",
		Docs:      "concepts/goldens",
		Retryable: false,
		ExitCode:  ExitProvider,
	},
	AFDB005: {
		Code:      AFDB005,
		Area:      "DB",
		Message:   "The golden version {version} is still referenced by {count} environments and cannot be collected.",
		NextStep:  "Run 'af down' on those environments first, or leave the version in place.",
		Docs:      "concepts/goldens",
		Retryable: false,
		ExitCode:  ExitPolicyDenied,
	},
	AFDB006: {
		Code:      AFDB006,
		Area:      "DB",
		Message:   "The provider's concurrent branch limit ({limit}) is reached.",
		NextStep:  "Run 'af down' on unused environments or raise the limit in the provider settings.",
		Docs:      "providers/limits",
		Retryable: false,
		ExitCode:  ExitProvider,
	},
	AFDB007: {
		Code:      AFDB007,
		Area:      "DB",
		Message:   "Extension {extension} is required by the golden and is not available on the target.",
		NextStep:  "Install {extension} on the target, or remove its use from the schema before refreshing.",
		Docs:      "providers/overview",
		Retryable: false,
		ExitCode:  ExitProvider,
	},
	AFDB008: {
		Code:      AFDB008,
		Area:      "DB",
		Message:   "The database provider {provider} at {endpoint} rejected the configured credential.",
		NextStep:  "Check the value of the variable named by database.api_key_env; the provider answered 401, so the credential reached it and was refused rather than being missing.",
		Docs:      "providers/overview",
		Retryable: false,
		ExitCode:  ExitAuth,
	},
	AFDB009: {
		Code:      AFDB009,
		Area:      "DB",
		Message:   "The Database Lab Engine at {endpoint} has no snapshot to build a golden from: {detail}",
		NextStep:  "Wait for the engine's own data retrieval to finish, then refresh again; its progress is at GET /instance/retrieval.",
		Docs:      "providers/dblab",
		Retryable: true,
		ExitCode:  ExitProvider,
	},
	AFDB010: {
		Code:      AFDB010,
		Area:      "DB",
		Message:   "The storage pool has {available} free and the operation needs {needed}.",
		NextStep:  "Run 'af golden gc' to reclaim unreferenced versions, or grow the pool.",
		Docs:      "concepts/goldens",
		Retryable: false,
		ExitCode:  ExitProvider,
	},
	AFDB011: {
		Code:      AFDB011,
		Area:      "DB",
		Message:   "The subset could not be taken: {detail}",
		NextStep:  "Run 'af explain' to see the effective subset block, and check that the seed table and its predicate name columns this database has.",
		Docs:      "concepts/subsetting",
		Retryable: false,
		ExitCode:  ExitAuth,
	},
	AFDB012: {
		Code:      AFDB012,
		Area:      "DB",
		Message:   "No golden matches this manifest's masking rules, and {count} were made under different ones.",
		NextStep:  "Run 'af golden refresh' to make one from the source this manifest names.",
		Docs:      "concepts/goldens",
		Retryable: false,
		ExitCode:  ExitProvider,
	},
	AFDB013: {
		Code:      AFDB013,
		Area:      "DB",
		Message:   "The database seed command failed: {detail}",
		NextStep:  "Run the command yourself against an empty database of the same version. It is: {command}",
		Docs:      "concepts/goldens",
		Retryable: false,
		ExitCode:  ExitProvider,
	},
	AFDB014: {
		Code:      AFDB014,
		Area:      "DB",
		Message:   "No database branch exists for {env}.",
		NextStep:  "Run 'af up' to create one. This is not a missing golden: nothing has been branched for this environment yet.",
		Docs:      "concepts/goldens",
		Retryable: false,
		ExitCode:  ExitProvider,
	},
	AFDB020: {
		Code:      AFDB020,
		Area:      "DB",
		Message:   "Personas cannot be provisioned because {provider} creates users only through its own API, and no sandbox tenant is configured.",
		NextStep:  "Point auth.url or auth.domain at a sandbox, development or staging tenant and set auth.sandbox: true, so that personas are never created in production.",
		Docs:      "guides/personas",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFDB021: {
		Code:      AFDB021,
		Area:      "DB",
		Message:   "{provider} rejected the admin token used to create personas.",
		NextStep:  "Check that the variable named by auth.token_env holds a key for the sandbox tenant with permission to create users.",
		Docs:      "guides/personas",
		Retryable: false,
		ExitCode:  ExitAuth,
	},
	AFDB030: {
		Code:      AFDB030,
		Area:      "DB",
		Message:   "Migrations failed on the branch: {detail}",
		NextStep:  "The rehearsal names the statement that failed and times the ones before it. Fix the migration and push again: a migration that fails on a branch with production's shape is one that would have failed in production.",
		Docs:      "concepts/insights",
		Retryable: false,
		ExitCode:  ExitProvider,
	},
	AFDB031: {
		Code:      AFDB031,
		Area:      "DB",
		Message:   "The migration finding {rule} fails this project's policy: {detail}",
		NextStep:  "The report above names the table and the statement. Fix the migration, or lower the rule to 'warn' in the manifest's policy block.",
		Docs:      "concepts/verdicts",
		Retryable: false,
		ExitCode:  ExitTestFailure,
	},
	AFDB032: {
		Code:      AFDB032,
		Area:      "DB",
		Message:   "The previous release does not survive this migration: {detail}",
		NextStep:  "A rolling deploy runs both releases at once, so make the change backward compatible: add the new column and write to both, migrate the readers, and drop the old one in a later deploy.",
		Docs:      "concepts/insights",
		Retryable: false,
		ExitCode:  ExitTestFailure,
	},
	AFDET001: {
		Code:      AFDET001,
		Area:      "DET",
		Message:   "No application could be detected in {path}.",
		NextStep:  "Declare your services by hand in antifailure.yaml; the manifest reference lists the minimum fields.",
		Docs:      "concepts/detection",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFDET002: {
		Code:      AFDET002,
		Area:      "DET",
		Message:   "Detection stopped after {budget} with partial results.",
		NextStep:  "Add large directories to .gitignore or .dockerignore, or pass --detect-timeout to raise the budget.",
		Docs:      "concepts/detection",
		Retryable: true,
		ExitCode:  ExitConfiguration,
	},
	AFDET004: {
		Code:      AFDET004,
		Area:      "DET",
		Message:   "Detection could not decide {question}, and there is no default to fall back on.",
		NextStep:  "Answer it with --answer {id}=<value>, or run 'af init' from a terminal so it can ask.",
		Docs:      "concepts/detection",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFDET005: {
		Code:      AFDET005,
		Area:      "DET",
		Message:   "Detection produced a draft that is not a valid manifest, so nothing was written and {path} does not exist: {detail}",
		NextStep:  "Re-run with --answer to override what detection read, for example --answer service.<name>.port=<port>. If nothing in the repository is wrong, this is a defect in Antifailure and worth reporting with the detail above.",
		Docs:      "concepts/detection",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFDET006: {
		Code:      AFDET006,
		Area:      "DET",
		Message:   "--answer {id}=... does not name anything in this repository.",
		NextStep:  "Use one of: {known}",
		Docs:      "concepts/detection",
		Retryable: false,
		ExitCode:  ExitUsage,
	},
	AFDET010: {
		Code:      AFDET010,
		Area:      "DET",
		Message:   "The changed files between {base} and {head} could not be read: {detail}",
		NextStep:  "Fetch the base branch before running 'af change'. A checkout cloned one commit deep shares no history with it, which is what 'fetch-depth: 0' fixes in a GitHub Actions job.",
		Docs:      "concepts/change-analysis",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFDET011: {
		Code:      AFDET011,
		Area:      "DET",
		Message:   "The diff at {path} could not be read: {detail}",
		NextStep:  "Produce it with 'git diff --unified=0 base...head'; this reads git's own unified format and nothing else.",
		Docs:      "concepts/change-analysis",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFEE001: {
		Code:      AFEE001,
		Area:      "EE",
		Message:   "The enterprise license could not be verified.",
		NextStep:  "Reinstall the license with 'af license install'; the token may have been truncated in transit.",
		Docs:      "enterprise/licensing",
		Retryable: false,
		ExitCode:  ExitAuth,
	},
	AFEE002: {
		Code:      AFEE002,
		Area:      "EE",
		Message:   "The system clock is {skew} behind the last time this license was seen.",
		NextStep:  "Correct the system clock. Enterprise features resume once it passes the recorded time.",
		Docs:      "enterprise/licensing",
		Retryable: true,
		ExitCode:  ExitAuth,
	},
	AFEE003: {
		Code:      AFEE003,
		Area:      "EE",
		Message:   "This license was issued for organization {issued_for} and this instance is {actual}.",
		NextStep:  "Install the license issued for {actual}.",
		Docs:      "enterprise/licensing",
		Retryable: false,
		ExitCode:  ExitAuth,
	},
	AFEE004: {
		Code:      AFEE004,
		Area:      "EE",
		Message:   "The license covers {seats} seats and they are all in use.",
		NextStep:  "Remove an inactive member, or contact licensing@antifailure.dev to add seats. No existing member was removed.",
		Docs:      "enterprise/licensing",
		Retryable: false,
		ExitCode:  ExitPolicyDenied,
	},
	AFEE010: {
		Code:      AFEE010,
		Area:      "EE",
		Message:   "Organization policy {policy} refuses this environment: {detail}",
		NextStep:  "Ask an organization administrator to review {policy}, or bring the repository into compliance.",
		Docs:      "enterprise/policy",
		Retryable: false,
		ExitCode:  ExitPolicyDenied,
	},
	AFFID001: {
		Code:      AFFID001,
		Area:      "FID",
		Message:   "The environment does not reproduce {dimension}, which the manifest requires: {detail}",
		NextStep:  "Fix what the inventory names, or remove {dimension} from fidelity.require.",
		Docs:      "concepts/inventory",
		Retryable: false,
		ExitCode:  ExitPolicyDenied,
	},
	AFFID002: {
		Code:      AFFID002,
		Area:      "FID",
		Message:   "{dimension} is required and could not be measured, so it is neither met nor broken: {detail}",
		NextStep:  "Run 'af fidelity' to see what could not be measured, and fix that before trusting the requirement.",
		Docs:      "concepts/inventory",
		Retryable: false,
		ExitCode:  ExitFailure,
	},
	AFGH001: {
		Code:      AFGH001,
		Area:      "GH",
		Message:   "The webhook signature did not verify.",
		NextStep:  "Confirm that the webhook secret stored for this installation matches the one configured in GitHub.",
		Docs:      "guides/github",
		Retryable: false,
		ExitCode:  ExitAuth,
	},
	AFGH002: {
		Code:      AFGH002,
		Area:      "GH",
		Message:   "The GitHub API rejected the request: {detail}",
		NextStep:  "Check the App's permissions against the list on the GitHub integration page.",
		Docs:      "guides/github",
		Retryable: false,
		ExitCode:  ExitAuth,
	},
	AFINF001: {
		Code:      AFINF001,
		Area:      "INF",
		Message:   "The cloud API returned a quota error for {quota} in {region}.",
		NextStep:  "Request more {quota} in {region}, then run the command again.",
		Docs:      "self-hosting/azure",
		Retryable: false,
		ExitCode:  ExitProvider,
	},
	AFINF002: {
		Code:      AFINF002,
		Area:      "INF",
		Message:   "The provider rate limited this operation and asked to wait {retry_after}.",
		NextStep:  "The engine retries automatically. If this persists, lower the concurrency in the manifest.",
		Docs:      "providers/limits",
		Retryable: true,
		ExitCode:  ExitProvider,
	},
	AFLOD001: {
		Code:      AFLOD001,
		Area:      "LOD",
		Message:   "The load target {target} is not an environment this engine created.",
		NextStep:  "Point the load run at an environment from 'af status'. Load is never generated against an external host.",
		Docs:      "concepts/load",
		Retryable: false,
		ExitCode:  ExitPolicyDenied,
	},
	AFLOD002: {
		Code:      AFLOD002,
		Area:      "LOD",
		Message:   "The load run was aborted after the error rate exceeded {threshold} for {duration}.",
		NextStep:  "The service is failing under this load. The report above shows the first failing endpoint.",
		Docs:      "concepts/load",
		Retryable: false,
		ExitCode:  ExitTestFailure,
	},
	AFLOD010: {
		Code:      AFLOD010,
		Area:      "LOD",
		Message:   "Load could not be generated: {detail}",
		NextStep:  "Bring the environment up with 'af up', and check the load section of the manifest.",
		Docs:      "concepts/load",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFLOD011: {
		Code:      AFLOD011,
		Area:      "LOD",
		Message:   "Load exceeded {count} thresholds the manifest sets.",
		NextStep:  "The breaches are listed above, worst first. Raise the threshold or fix the regression.",
		Docs:      "concepts/load",
		Retryable: false,
		ExitCode:  ExitTestFailure,
	},
	AFLOD012: {
		Code:      AFLOD012,
		Area:      "LOD",
		Message:   "There is no load source called {source}.",
		NextStep:  "Use otel for an OpenTelemetry trace export, access_log for a combined format log, or none. Both file sources read source_config.path.",
		Docs:      "concepts/load",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFLOD013: {
		Code:      AFLOD013,
		Area:      "LOD",
		Message:   "The scenario at {path} could not be read: {detail}",
		NextStep:  "Fix the document, then run 'af doctor' to revalidate the manifest.",
		Docs:      "concepts/load",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFLOD014: {
		Code:      AFLOD014,
		Area:      "LOD",
		Message:   "{count} scenario assertions did not hold.",
		NextStep:  "Each one is listed above with what it measured. Fix the regression, or change what the scenario asks for.",
		Docs:      "concepts/load",
		Retryable: false,
		ExitCode:  ExitTestFailure,
	},
	AFLOD015: {
		Code:      AFLOD015,
		Area:      "LOD",
		Message:   "The scenario {scenario} proved nothing: {detail}",
		NextStep:  "A scenario is blocked when a route it sends is not named in load.safe_routes, and unverified when an assertion names a step that nothing sent. Both are fixed in the manifest or in the scenario document.",
		Docs:      "concepts/load",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFLOD016: {
		Code:      AFLOD016,
		Area:      "LOD",
		Message:   "The p95_increase threshold proved nothing: {detail}",
		NextStep:  "The threshold divides a measured p95 by production's own p95 for that route, and only a trace export carries one. Read the traffic with source: otel, or judge the run on error_rate alone.",
		Docs:      "concepts/load",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFMAN001: {
		Code:      AFMAN001,
		Area:      "MAN",
		Message:   "No antifailure.yaml was found in {path} or any parent directory.",
		NextStep:  "Run 'af init' in the repository root to create one.",
		Docs:      "reference/manifest",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFMAN002: {
		Code:      AFMAN002,
		Area:      "MAN",
		Message:   "The manifest at {path} is not valid: {detail}",
		NextStep:  "Fix the reported line, then run 'af doctor' to revalidate.",
		Docs:      "reference/manifest",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFMAN003: {
		Code:      AFMAN003,
		Area:      "MAN",
		Message:   "The manifest at {path} declares schema version {found}, which this build does not understand.",
		NextStep:  "Upgrade with 'af version -check' and install the release that supports version {found}.",
		Docs:      "reference/manifest",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFMAN004: {
		Code:      AFMAN004,
		Area:      "MAN",
		Message:   "'af init' has questions to ask and this session has no terminal to ask them on.",
		NextStep:  "Pass --non-interactive to accept every default, and --answer id=value for anything that has no default.",
		Docs:      "reference/cli#af-init",
		Retryable: false,
		ExitCode:  ExitUsage,
	},
	AFMAN005: {
		Code:      AFMAN005,
		Area:      "MAN",
		Message:   "The manifest at {path} is larger than the {limit} limit.",
		NextStep:  "Split the configuration or remove generated content; a manifest describes services, it does not contain them.",
		Docs:      "reference/manifest",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFMAN006: {
		Code:      AFMAN006,
		Area:      "MAN",
		Message:   "The path {path} in the manifest resolves outside the repository.",
		NextStep:  "Use a path relative to the repository root, with no leading slash and no parent directory segments.",
		Docs:      "reference/manifest",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFMSK001: {
		Code:      AFMSK001,
		Area:      "MSK",
		Message:   "The golden {version} has no valid verification attestation and cannot be branched.",
		NextStep:  "Run 'af golden verify {version}'; a golden is branchable only once verification has passed.",
		Docs:      "concepts/verification",
		Retryable: false,
		ExitCode:  ExitVerification,
	},
	AFMSK002: {
		Code:      AFMSK002,
		Area:      "MSK",
		Message:   "Verification found data matching {detector} in {table}.{column}.",
		NextStep:  "Add a masking rule for {table}.{column} and refresh the golden. The value itself is never printed.",
		Docs:      "concepts/verification",
		Retryable: false,
		ExitCode:  ExitVerification,
	},
	AFMSK003: {
		Code:      AFMSK003,
		Area:      "MSK",
		Message:   "The masking rule for {table}.{column} names a column that does not exist in the schema.",
		NextStep:  "Remove the rule or correct the name; 'af mask plan' lists the columns it found.",
		Docs:      "concepts/masking",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFMSK004: {
		Code:      AFMSK004,
		Area:      "MSK",
		Message:   "Masking would violate the check constraint {constraint} on {table}.{column}.",
		NextStep:  "Choose a format preserving transform for {table}.{column} that satisfies {constraint}.",
		Docs:      "reference/transforms",
		Retryable: false,
		ExitCode:  ExitVerification,
	},
	AFMSK005: {
		Code:      AFMSK005,
		Area:      "MSK",
		Message:   "Masking is only permitted on a golden candidate, and {target} is a source database.",
		NextStep:  "Run masking against a golden candidate; the engine never rewrites a source.",
		Docs:      "concepts/masking",
		Retryable: false,
		ExitCode:  ExitPolicyDenied,
	},
	AFMSK007: {
		Code:      AFMSK007,
		Area:      "MSK",
		Message:   "The transform on {table}.{column} produced duplicate values under the unique constraint {constraint}.",
		NextStep:  "Use a transform that preserves uniqueness, such as email or uuid_remap, for {table}.{column}.",
		Docs:      "reference/transforms",
		Retryable: false,
		ExitCode:  ExitVerification,
	},
	AFMSK008: {
		Code:      AFMSK008,
		Area:      "MSK",
		Message:   "The columns {columns} hold free text and have no masking rule.",
		NextStep:  "Give each column a rule, or allowlist it explicitly if it is known to hold no personal data.",
		Docs:      "concepts/masking",
		Retryable: false,
		ExitCode:  ExitVerification,
	},
	AFMSK010: {
		Code:      AFMSK010,
		Area:      "MSK",
		Message:   "Masking could not run: {detail}",
		NextStep:  "Run 'af mask plan' to see what was decided for each column.",
		Docs:      "concepts/masking",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFNET001: {
		Code:      AFNET001,
		Area:      "NET",
		Message:   "The request to {host} was blocked by rule {rule}.",
		NextStep:  "Add an egress rule for {host} with the mode you intend, or leave it blocked.",
		Docs:      "concepts/egress",
		Retryable: false,
		ExitCode:  ExitPolicyDenied,
	},
	AFNET002: {
		Code:      AFNET002,
		Area:      "NET",
		Message:   "{request} is not a request that can be explained: {detail}",
		NextStep:  "Pass a method and a URL, as in 'af net explain GET https://api.stripe.com/v1/charges'.",
		Docs:      "reference/cli#af-net-explain",
		Retryable: false,
		ExitCode:  ExitUsage,
	},
	AFNET004: {
		Code:      AFNET004,
		Area:      "NET",
		Message:   "A request to {host} carried a live credential in the {header} header and was blocked.",
		NextStep:  "Replace the credential with a sandbox key; an environment must never hold a live one.",
		Docs:      "concepts/egress",
		Retryable: false,
		ExitCode:  ExitPolicyDenied,
	},
	AFNET005: {
		Code:      AFNET005,
		Area:      "NET",
		Message:   "The sandbox credential for {host} was rejected: {detail}",
		NextStep:  "Check the sandbox key's permissions at the provider.",
		Docs:      "guides/sandbox",
		Retryable: false,
		ExitCode:  ExitAuth,
	},
	AFNET010: {
		Code:      AFNET010,
		Area:      "NET",
		Message:   "No mock matched {method} {path} on {host}.",
		NextStep:  "A fixture skeleton was written to {suggestion}. Fill it in and run again.",
		Docs:      "guides/mocking",
		Retryable: false,
		ExitCode:  ExitPolicyDenied,
	},
	AFNET011: {
		Code:      AFNET011,
		Area:      "NET",
		Message:   "No message matching {match} arrived within {timeout}.",
		NextStep:  "Check 'af net log' to see whether the request was refused, and 'af inbox list' for what did arrive.",
		Docs:      "guides/inbox",
		Retryable: true,
		ExitCode:  ExitTestFailure,
	},
	AFNET012: {
		Code:      AFNET012,
		Area:      "NET",
		Message:   "The webhook could not be delivered to {service}: {detail}",
		NextStep:  "Run 'af status' to check the service is up, and check the path against the manifest's webhook_path.",
		Docs:      "guides/webhooks",
		Retryable: true,
		ExitCode:  ExitFailure,
	},
	AFNET013: {
		Code:      AFNET013,
		Area:      "NET",
		Message:   "The environment tried to reach {hosts}, which nothing in the manifest mentions.",
		NextStep:  "Add an egress rule for it with the mode you intend, or set policy.egress_surprise to 'warn' to let the attempt through the check.",
		Docs:      "concepts/verdicts",
		Retryable: false,
		ExitCode:  ExitPolicyDenied,
	},
	AFNET020: {
		Code:      AFNET020,
		Area:      "NET",
		Message:   "{host} rejected the environment certificate, which usually means the client pins its own.",
		NextStep:  "Set the host to ALLOW so that its traffic is not intercepted, or disable pinning in the client for previews.",
		Docs:      "concepts/egress",
		Retryable: false,
		ExitCode:  ExitPolicyDenied,
	},
	AFNET021: {
		Code:      AFNET021,
		Area:      "NET",
		Message:   "{host} resolves only to IPv6 and the environment has IPv6 disabled.",
		NextStep:  "Set egress.allow_ipv6 for this environment, or use a host with an IPv4 address.",
		Docs:      "concepts/egress",
		Retryable: false,
		ExitCode:  ExitPolicyDenied,
	},
	AFNET030: {
		Code:      AFNET030,
		Area:      "NET",
		Message:   "The synthesis model returned no usable response for {method} {path}.",
		NextStep:  "SYNTH is an escape hatch, not a pass. Write a fixture for this endpoint instead.",
		Docs:      "guides/synth",
		Retryable: true,
		ExitCode:  ExitProvider,
	},
	AFORC001: {
		Code:      AFORC001,
		Area:      "ORC",
		Message:   "The manifest declares no oracle block, so there is nothing to compare.",
		NextStep:  "Add an oracle block with at least one probe; the manifest reference has the shape.",
		Docs:      "concepts/oracle",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFORC002: {
		Code:      AFORC002,
		Area:      "ORC",
		Message:   "The oracle is on and declares no requests to send.",
		NextStep:  "Add at least one entry under oracle.probes. Both versions have to receive the same requests in the same order, so the plan is written down rather than discovered.",
		Docs:      "concepts/oracle",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFORC003: {
		Code:      AFORC003,
		Area:      "ORC",
		Message:   "The baseline revision could not be resolved: {detail}",
		NextStep:  "Set oracle.base_ref to a branch, tag, or commit this checkout can see, and fetch it if it is a remote ref.",
		Docs:      "concepts/oracle",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFORC004: {
		Code:      AFORC004,
		Area:      "ORC",
		Message:   "The baseline and the candidate are both {commit}, so there is nothing to compare.",
		NextStep:  "Commit the change, or point oracle.base_ref at the revision you meant to compare against.",
		Docs:      "concepts/oracle",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFORC005: {
		Code:      AFORC005,
		Area:      "ORC",
		Message:   "The baseline revision {commit} could not be checked out: {detail}",
		NextStep:  "Check that the commit is present in this clone; a shallow clone often is not deep enough to reach it.",
		Docs:      "concepts/oracle",
		Retryable: true,
		ExitCode:  ExitProvider,
	},
	AFORC006: {
		Code:      AFORC006,
		Area:      "ORC",
		Message:   "There is no web service to send requests to in the {side} environment.",
		NextStep:  "Declare a service of kind web in the manifest; the oracle compares HTTP responses and needs somewhere to send them.",
		Docs:      "concepts/oracle",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFORC007: {
		Code:      AFORC007,
		Area:      "ORC",
		Message:   "The baseline environment did not come up: {detail}",
		NextStep:  "Bring the baseline revision up on its own with 'af up' from a checkout of it to see the build or migration failure in full.",
		Docs:      "concepts/oracle",
		Retryable: true,
		ExitCode:  ExitProvider,
	},
	AFORC008: {
		Code:      AFORC008,
		Area:      "ORC",
		Message:   "The {side} branch could not be read for comparison: {detail}",
		NextStep:  "Check the branch is reachable, or turn the contents comparison off with oracle.database.enabled: false to compare responses alone.",
		Docs:      "concepts/oracle",
		Retryable: true,
		ExitCode:  ExitProvider,
	},
	AFORC009: {
		Code:      AFORC009,
		Area:      "ORC",
		Message:   "The golden version {version} the comparison pinned is no longer present or no longer verified.",
		NextStep:  "Run the comparison again; both sides branch one golden and the one the candidate used has gone.",
		Docs:      "concepts/oracle",
		Retryable: true,
		ExitCode:  ExitProvider,
	},
	AFORC010: {
		Code:      AFORC010,
		Area:      "ORC",
		Message:   "The candidate behaves differently from the baseline: {detail}",
		NextStep:  "Read the differences above. Each one is either the change you meant to make or a regression; raise oracle.fail_on if this class of difference is expected.",
		Docs:      "concepts/oracle",
		Retryable: false,
		ExitCode:  ExitTestFailure,
	},
	AFRUN001: {
		Code:      AFRUN001,
		Area:      "RUN",
		Message:   "The command '{command}' is not available in this version.",
		NextStep:  "See the roadmap for when it lands; 'af version' reports the version you are running.",
		Docs:      "reference/cli",
		Retryable: false,
		ExitCode:  ExitUsage,
	},
	AFRUN002: {
		Code:      AFRUN002,
		Area:      "RUN",
		Message:   "The Docker daemon at {endpoint} could not be reached.",
		NextStep:  "Start Docker and run 'af doctor' to confirm; on macOS that is Docker Desktop.",
		Docs:      "guides/local-runtime",
		Retryable: true,
		ExitCode:  ExitProvider,
	},
	AFRUN003: {
		Code:      AFRUN003,
		Area:      "RUN",
		Message:   "Another Antifailure process holds the lock for this branch (process {pid}, since {since}).",
		NextStep:  "Wait for it to finish, or stop it and run 'af down' to clean up.",
		Docs:      "concepts/journal",
		Retryable: true,
		ExitCode:  ExitFailure,
	},
	AFRUN004: {
		Code:      AFRUN004,
		Area:      "RUN",
		Message:   "Service {service} did not become ready within {timeout}.",
		NextStep:  "The last log lines are above. Check the health path {health} and the port the service binds.",
		Docs:      "guides/local-runtime",
		Retryable: true,
		ExitCode:  ExitFailure,
	},
	AFRUN005: {
		Code:      AFRUN005,
		Area:      "RUN",
		Message:   "Service {service} exited with code {code} during startup.",
		NextStep:  "The last log lines are above. Run 'af logs {service}' for the full output.",
		Docs:      "guides/local-runtime",
		Retryable: false,
		ExitCode:  ExitFailure,
	},
	AFRUN009: {
		Code:      AFRUN009,
		Area:      "RUN",
		Message:   "No free port was found in the range {range} to publish the environment on.",
		NextStep:  "Free a port in that range, or set AF_PORT_RANGE_START to the first port of a range that is clear.",
		Docs:      "guides/local-runtime",
		Retryable: true,
		ExitCode:  ExitFailure,
	},
	AFRUN010: {
		Code:      AFRUN010,
		Area:      "RUN",
		Message:   "Writing to {path} failed because the disk is full; {needed} is required.",
		NextStep:  "Free space on the volume holding {path}, then run the command again.",
		Docs:      "guides/local-runtime",
		Retryable: true,
		ExitCode:  ExitFailure,
	},
	AFRUN011: {
		Code:      AFRUN011,
		Area:      "RUN",
		Message:   "The local state database at {path} is corrupt.",
		NextStep:  "A backup was written to {backup}. The database was rebuilt, so it now tracks nothing: run 'af env list' to see what is still running and 'af env prune --older-than 0' to remove all of it.",
		Docs:      "concepts/journal",
		Retryable: false,
		ExitCode:  ExitFailure,
	},
	AFRUN020: {
		Code:      AFRUN020,
		Area:      "RUN",
		Message:   "Docker has no room left for the environment: {detail}",
		NextStep:  "Run 'docker system prune' or raise the disk limit in Docker's settings.",
		Docs:      "guides/local-runtime",
		Retryable: true,
		ExitCode:  ExitProvider,
	},
	AFRUN030: {
		Code:      AFRUN030,
		Area:      "RUN",
		Message:   "The environment could not be torn down completely; {count} resources are still recorded.",
		NextStep:  "Run 'af down' again once the provider is reachable; the journal remembers what is left.",
		Docs:      "concepts/journal",
		Retryable: true,
		ExitCode:  ExitInterruptedDirty,
	},
	AFRUN040: {
		Code:      AFRUN040,
		Area:      "RUN",
		Message:   "The environment could not be placed: {detail}",
		NextStep:  "Run 'af doctor' to check the runtime, then 'af down' to clear anything left behind.",
		Docs:      "guides/local-runtime",
		Retryable: true,
		ExitCode:  ExitFailure,
	},
	AFRUN041: {
		Code:      AFRUN041,
		Area:      "RUN",
		Message:   "The services depend on each other in a cycle: {cycle}",
		NextStep:  "Remove one of the depends_on entries; a cycle has no order that can start.",
		Docs:      "reference/manifest",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFRUN042: {
		Code:      AFRUN042,
		Area:      "RUN",
		Message:   "Service {service} depends on {missing}, which the manifest does not declare.",
		NextStep:  "Add a service called {missing}, or correct the depends_on entry.",
		Docs:      "reference/manifest",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFRUN043: {
		Code:      AFRUN043,
		Area:      "RUN",
		Message:   "This cluster is not containing the environment: {detail}",
		NextStep:  "Use a cluster whose CNI enforces NetworkPolicy rather than only accepting it, then run 'af up' again.",
		Docs:      "guides/kubernetes-runtime",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFRUN044: {
		Code:      AFRUN044,
		Area:      "RUN",
		Message:   "This runtime cannot do that: {detail}",
		NextStep:  "Use the runtime that supports it, or run the command against an environment placed by one that does.",
		Docs:      "guides/kubernetes-runtime",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFRUN045: {
		Code:      AFRUN045,
		Area:      "RUN",
		Message:   "{kind} {name} was not created by this runtime, so it was not removed.",
		NextStep:  "Remove it yourself if you meant to, or use an environment id this runtime placed. 'af env list' shows the ones it owns.",
		Docs:      "guides/kubernetes-runtime",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFRUN046: {
		Code:      AFRUN046,
		Area:      "RUN",
		Message:   "AF_PORT_RANGE_START is set to {value}, which is not a port number.",
		NextStep:  "Set it to the first port of a free range, between {limit}, or unset it to use the default.",
		Docs:      "guides/local-runtime",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFSCH001: {
		Code:      AFSCH001,
		Area:      "SCH",
		Message:   "No runtime satisfies the placement requirement {requirement}.",
		NextStep:  "Register a runtime that meets it, or relax the requirement in the placement rules.",
		Docs:      "enterprise/runtimes",
		Retryable: false,
		ExitCode:  ExitProvider,
	},
	AFSCH002: {
		Code:      AFSCH002,
		Area:      "SCH",
		Message:   "The organization is at its concurrent environment limit ({limit}); this run is queued at position {position}.",
		NextStep:  "It will start automatically. Tear down an unused environment to start sooner.",
		Docs:      "concepts/scheduling",
		Retryable: true,
		ExitCode:  ExitProvider,
	},
	AFSEC001: {
		Code:      AFSEC001,
		Area:      "SEC",
		Message:   "The variables {names} are declared in the manifest but were not found in any configured source.",
		NextStep:  "Add them to one of the searched sources: {sources}.",
		Docs:      "guides/secrets",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFSEC002: {
		Code:      AFSEC002,
		Area:      "SEC",
		Message:   "The credential for {source} was rejected after one refresh: {detail}",
		NextStep:  "Rotate the credential and store the new value where {source} reads it. A rejection that survives a refresh is a credential that was revoked or was never right, so retrying will not help.",
		Docs:      "guides/secrets",
		Retryable: false,
		ExitCode:  ExitAuth,
	},
	AFSEC003: {
		Code:      AFSEC003,
		Area:      "SEC",
		Message:   "The value supplied for {name} carries a live credential prefix, and {name} is configured for sandbox use.",
		NextStep:  "Point {name} at a sandbox credential; the environment must never hold a live key.",
		Docs:      "guides/secrets",
		Retryable: false,
		ExitCode:  ExitPolicyDenied,
	},
	AFSEC004: {
		Code:      AFSEC004,
		Area:      "SEC",
		Message:   "The encrypted local store has no passphrase: no system keyring answered and AF_SECRET_PASSPHRASE is not set.",
		NextStep:  "Set AF_SECRET_PASSPHRASE, or store the passphrase in the system keyring on a platform that has one. There is deliberately no default: a store encrypted with a passphrase everybody knows only looks encrypted.",
		Docs:      "guides/secrets",
		Retryable: false,
		ExitCode:  ExitConfiguration,
	},
	AFSEC010: {
		Code:      AFSEC010,
		Area:      "SEC",
		Message:   "The environment certificate could not be created: {detail}",
		NextStep:  "Run 'af doctor' to check the runtime, then bring the environment up again.",
		Docs:      "concepts/egress",
		Retryable: true,
		ExitCode:  ExitFailure,
	},
}
