package iac

import (
	"sort"
	"strings"
)

// The typed extractors, for the resource types this reader has been taught.
//
// Everything reaches a Reading through genericAttrs already, so these add the
// TYPED fields on top: the image, the replica counts, the environment variable
// names, the secret references, the probes. A resource type with no extractor
// here is still described, just less specifically, and that is the property
// that stops this file from being a list somebody has to finish before the
// package is useful.
//
// WRITTEN AGAINST A REAL SAMPLE rather than against provider documentation:
// infra/terraform/modules/control-plane/app.tf in this repository is a
// 250 line azurerm_container_app with dynamic secret blocks, dynamic env
// blocks, a scale rule and an ingress, and it is the fixture the container app
// extractor was built to read. See the dogfood test.

// presenceOf reads a resource's count and for_each into the answer "is this in
// production".
//
// The three answers matter separately. `count = 0` is declared and
// deliberately not deployed. `count = var.thing_enabled ? 1 : 0` is declared
// and this reader cannot say, which is the common case and the one a guess
// would get wrong half the time. No count at all is simply present.
func presenceOf(ctx *evalCtx, body hclBody, at Position) Value[bool] {
	if a, ok := body.attr("count"); ok {
		v := ctx.eval(a.expr)
		switch {
		case v.st == Unreadable:
			return Unresolved[bool]("its count is not something this reader can resolve, so "+
				"whether production has it is decided when Terraform runs: "+v.why, at)
		case v.st == Known && v.kind == cvalScalar:
			if v.s == "0" {
				return Resolved(false, at)
			}
			return Resolved(true, at)
		}
	}
	if a, ok := body.attr("for_each"); ok {
		v := ctx.eval(a.expr)
		if v.st == Unreadable {
			return Unresolved[bool]("its for_each is not something this reader can resolve, so "+
				"how many of it production has is decided when Terraform runs: "+v.why, at)
		}
		if v.st == Known && v.kind == cvalList && len(v.list) == 0 {
			return Resolved(false, at)
		}
	}
	return Resolved(true, at)
}

// readContainerApp reads an azurerm_container_app.
func readContainerApp(ctx *evalCtx, c *Component, body hclBody, file string) {
	// The app's own secret blocks: a name and the vault secret it is fed from.
	// The key_vault_secret_id is a LOCATOR, and carrying it is the whole point
	// of a secret reference; sensitive.go's locator rule is what lets it
	// through while `value` on a key vault secret is dropped.
	for _, blk := range body.blocksOf("secret") {
		prev := ctx.enterBlock(blk)
		at := Position{File: file, Line: blk.pos.Line, Col: blk.pos.Col}
		ref := SecretRef{At: at}
		if a, ok := blk.body.attr("name"); ok {
			ref.Name = ctx.eval(a.expr).str().Or("")
		}
		if a, ok := blk.body.attr("key_vault_secret_id"); ok {
			ref.From = valueAt(ctx.eval(a.expr), at)
		}
		if ref.Name == "" && blk.condWhy != "" {
			ref.Name = "a secret generated by a dynamic block"
			ref.From = Unresolved[string](blk.condWhy, at)
		}
		if ref.Name != "" {
			c.Secrets = append(c.Secrets, ref)
		}
		ctx.iterator = prev
	}

	tmpl, ok := body.firstBlock("template")
	if !ok {
		return
	}
	at := Position{File: file, Line: tmpl.pos.Line, Col: tmpl.pos.Col}
	if a, ok := tmpl.body.attr("min_replicas"); ok {
		c.Replicas = valueAtNum(ctx.eval(a.expr), Position{File: file, Line: a.pos.Line, Col: a.pos.Col})
	}

	containers := tmpl.body.blocksOf("container")
	if len(containers) == 0 {
		return
	}
	// A container app with several containers is a sidecar arrangement. The
	// component's own image is the FIRST container's, and the rest arrive as
	// attributes, because inventing one component per container would make
	// the sidecar look like a separate service in every report.
	main := containers[0]
	if a, ok := main.body.attr("image"); ok {
		c.Image = valueAt(ctx.eval(a.expr), Position{File: file, Line: a.pos.Line, Col: a.pos.Col})
	}
	if a, ok := main.body.attr("cpu"); ok {
		c.CPU = valueAt(ctx.eval(a.expr), Position{File: file, Line: a.pos.Line, Col: a.pos.Col})
	}
	if a, ok := main.body.attr("memory"); ok {
		c.Memory = valueAt(ctx.eval(a.expr), Position{File: file, Line: a.pos.Line, Col: a.pos.Col})
	}
	for _, blk := range main.body.blocksOf("env") {
		if v, ok := envOf(ctx, blk, file); ok {
			c.Env = append(c.Env, v)
		}
	}
	for _, probeType := range []string{"liveness_probe", "readiness_probe", "startup_probe"} {
		for _, blk := range main.body.blocksOf(probeType) {
			c.Probes = append(c.Probes, probeOf(ctx, strings.TrimSuffix(probeType, "_probe"), blk, file))
		}
	}
	sortEnv(c)
	_ = at
}

// envOf reads one env block into a name and, when it is fed from a secret,
// the secret's name.
func envOf(ctx *evalCtx, blk hclBlock, file string) (EnvVar, bool) {
	prev := ctx.enterBlock(blk)
	defer func() { ctx.iterator = prev }()
	at := Position{File: file, Line: blk.pos.Line, Col: blk.pos.Col}
	v := EnvVar{At: at, Present: Resolved(true, at)}
	if blk.condWhy != "" {
		v.Present = Unresolved[bool](blk.condWhy, at)
	}
	a, ok := blk.body.attr("name")
	if !ok {
		return EnvVar{}, false
	}
	name := ctx.eval(a.expr).str()
	got, known := name.Get()
	if !known {
		// A variable whose NAME cannot be resolved is still worth reporting,
		// because "there is another variable here and I cannot tell you what
		// it is called" is a fact about the environment's shape.
		v.Name = "an environment variable whose name this reader could not resolve"
		v.Present = Unresolved[bool](name.Why(), at)
		return v, true
	}
	v.Name = got
	if s, ok := blk.body.attr("secret_name"); ok {
		v.From = valueAt(ctx.eval(s.expr), at)
	}
	return v, true
}

// probeOf reads a health probe.
func probeOf(ctx *evalCtx, typ string, blk hclBlock, file string) Probe {
	prev := ctx.enterBlock(blk)
	defer func() { ctx.iterator = prev }()
	at := Position{File: file, Line: blk.pos.Line, Col: blk.pos.Col}
	p := Probe{Type: typ, At: at}
	str := func(names ...string) Value[string] {
		for _, n := range names {
			if a, ok := blk.body.attr(n); ok {
				return valueAt(ctx.eval(a.expr), Position{File: file, Line: a.pos.Line, Col: a.pos.Col})
			}
		}
		return Value[string]{}
	}
	num := func(names ...string) Value[int] {
		for _, n := range names {
			if a, ok := blk.body.attr(n); ok {
				return valueAtNum(ctx.eval(a.expr), Position{File: file, Line: a.pos.Line, Col: a.pos.Col})
			}
		}
		return Value[int]{}
	}
	p.Path = str("path")
	p.Port = str("port")
	p.Scheme = str("transport", "scheme")
	p.TimeoutSeconds = num("timeout", "timeout_seconds", "timeoutSeconds")
	p.PeriodSeconds = num("interval_seconds", "period_seconds", "periodSeconds")
	p.InitialDelaySeconds = num("initial_delay", "initial_delay_seconds", "initialDelaySeconds")
	p.FailureThreshold = num("failure_count_threshold", "failure_threshold", "failureThreshold")
	return p
}

func sortEnv(c *Component) {
	sort.SliceStable(c.Env, func(i, j int) bool { return c.Env[i].Name < c.Env[j].Name })
	sort.SliceStable(c.Secrets, func(i, j int) bool { return c.Secrets[i].Name < c.Secrets[j].Name })
}

func valueAtNum(v cval, at Position) Value[int] {
	n := v.num()
	if n.At().File != "" {
		return n
	}
	switch n.State() {
	case Known:
		got, _ := n.Get()
		return Resolved(got, at)
	case Unreadable:
		return Unresolved[int](n.Why(), at)
	case Withheld:
		return Refused[int](n.Why(), at)
	}
	return Value[int]{}
}

// networkRules reads the resource types that say what may talk to what.
//
// It returns false for everything else, which is how readResource knows a
// security group rule is not a component: a rule is not a thing production
// holds, it is a statement about what the things production holds may do.
func networkRules(ctx *evalCtx, resType, address string, at Position, blk hclBlock) ([]NetworkRule, bool) {
	get := func(body hclBody, names ...string) Value[string] {
		for _, n := range names {
			if a, ok := body.attr(n); ok {
				return valueAt(ctx.eval(a.expr), Position{File: at.File, Line: a.pos.Line, Col: a.pos.Col})
			}
		}
		return Value[string]{}
	}
	switch resType {
	case "aws_security_group":
		var out []NetworkRule
		for _, dir := range []struct {
			block string
			d     Direction
		}{{"egress", Egress}, {"ingress", Ingress}} {
			for i, rule := range blk.body.blocksOf(dir.block) {
				out = append(out, NetworkRule{
					Address:   address + "." + dir.block + "[" + itoa(i) + "]",
					Direction: dir.d,
					Allow:     true,
					Protocol:  get(rule.body, "protocol"),
					Ports:     portRange(ctx, rule.body, at),
					To:        get(rule.body, "cidr_blocks", "ipv6_cidr_blocks", "security_groups", "prefix_list_ids"),
					At:        at,
				})
			}
		}
		return out, true
	case "aws_security_group_rule", "aws_vpc_security_group_egress_rule", "aws_vpc_security_group_ingress_rule":
		d := Egress
		switch resType {
		case "aws_vpc_security_group_ingress_rule":
			d = Ingress
		case "aws_security_group_rule":
			if v := get(blk.body, "type"); v.Or("") == "ingress" {
				d = Ingress
			}
		}
		return []NetworkRule{{
			Address:   address,
			Direction: d,
			Allow:     true,
			Protocol:  get(blk.body, "ip_protocol", "protocol"),
			Ports:     portRange(ctx, blk.body, at),
			To:        get(blk.body, "cidr_ipv4", "cidr_ipv6", "cidr_blocks", "referenced_security_group_id", "source_security_group_id"),
			At:        at,
		}}, true
	case "azurerm_network_security_rule":
		d := Egress
		if v := get(blk.body, "direction"); strings.EqualFold(v.Or(""), "inbound") {
			d = Ingress
		}
		allow := true
		if v := get(blk.body, "access"); strings.EqualFold(v.Or("Allow"), "deny") {
			allow = false
		}
		return []NetworkRule{{
			Address:   address,
			Direction: d,
			Allow:     allow,
			Protocol:  get(blk.body, "protocol"),
			Ports:     get(blk.body, "destination_port_range", "destination_port_ranges"),
			To:        get(blk.body, "destination_address_prefix", "destination_address_prefixes"),
			At:        at,
		}}, true
	}
	return nil, false
}

// portRange renders a from/to pair the way a person reads it.
func portRange(ctx *evalCtx, body hclBody, at Position) Value[string] {
	from, hasFrom := body.attr("from_port")
	to, hasTo := body.attr("to_port")
	if !hasFrom && !hasTo {
		return Value[string]{}
	}
	f := valueAt(ctx.eval(from.expr), at)
	t := valueAt(ctx.eval(to.expr), at)
	fv, fok := f.Get()
	tv, tok := t.Get()
	switch {
	case fok && tok && fv == tv:
		return Resolved(fv, at)
	case fok && tok:
		return Resolved(fv+"-"+tv, at)
	case f.State() == Unreadable:
		return f
	case t.State() == Unreadable:
		return t
	}
	return Value[string]{}
}
