// The concrete sinks.
//
// Not MIT. Covered by the Antifailure Enterprise License; see ee/LICENSE.md.
//
// Each is small on purpose. The queue in sink.ts holds all the behaviour that
// is hard to get right, so a sink is only "put these bytes there", and adding a
// new destination is a page rather than a project.
//
// Every one of them takes its transport as a parameter. That is not for
// testing, or not only: it is what lets an operator route through their own
// proxy, pin a certificate, or add a header their gateway requires, without
// this package growing an option for each.
//
// What none of them does is retry. Retrying is the queue's job, and a sink that
// also retried would multiply the two and turn a brief outage into a thundering
// herd against somebody's log endpoint.

import { createHmac } from 'node:crypto'
import { PermanentError, type Batch, type Sink } from './sink.ts'

/** The fetch a sink uses. */
export type Fetcher = (url: string, init: RequestInit) => Promise<Response>

/**
 * Decides whether a status means "never going to work".
 *
 * 401 and 403 are a credential nobody is going to fix by waiting, and 400, 404,
 * and 413 are the request itself. Retrying any of them forever is how a queue
 * fills with one batch that will never be accepted. Everything else, including
 * 429 and every 5xx, is temporary and the queue's backoff handles it.
 */
function permanent(status: number): boolean {
  return status === 400 || status === 401 || status === 403 || status === 404 || status === 413
}

async function send(
  fetcher: Fetcher,
  url: string,
  init: RequestInit,
  what: string,
): Promise<void> {
  let res: Response
  try {
    res = await fetcher(url, init)
  } catch (err) {
    // A transport failure is temporary by assumption. A hostname that does not
    // resolve looks the same as one that is briefly unreachable, and guessing
    // wrong towards permanent would discard entries over a DNS blip.
    throw new Error(`${what}: ${err instanceof Error ? err.message : String(err)}`)
  }
  if (res.ok) return

  // Bounded, because an error path must not read an unbounded body from an
  // endpoint that may not be the one intended.
  const body = (await res.text().catch(() => '')).slice(0, 500)
  const message = `${what} answered ${res.status}${body ? `: ${body}` : ''}`
  throw permanent(res.status) ? new PermanentError(message) : new Error(message)
}

// ---------------------------------------------------------------------------

export interface SplunkOptions {
  /** The HTTP Event Collector endpoint, ending in /services/collector. */
  url: string
  token: string
  fetch: Fetcher
  /** Splunk's own index, source, and sourcetype, so entries land where the
   *  customer's existing searches already look rather than in main. */
  index?: string
  sourcetype?: string
}

/** Splunk's HTTP Event Collector, which takes newline-delimited JSON objects
 *  rather than an array. */
export class SplunkSink implements Sink {
  private readonly opts: SplunkOptions

  constructor(opts: SplunkOptions) {
    this.opts = opts
  }

  name(): string {
    return 'splunk'
  }

  async deliver(batch: Batch): Promise<void> {
    const body = batch.entries
      .map((entry) =>
        JSON.stringify({
          // Seconds, which is what HEC expects. Milliseconds are accepted and
          // silently interpreted as a date in the year 56000.
          time: Date.parse(entry.occurredAt) / 1000,
          host: 'antifailure',
          source: 'antifailure-audit',
          sourcetype: this.opts.sourcetype ?? 'antifailure:audit',
          ...(this.opts.index ? { index: this.opts.index } : {}),
          event: entry,
        }),
      )
      .join('\n')

    await send(
      this.opts.fetch,
      this.opts.url,
      {
        method: 'POST',
        headers: {
          authorization: `Splunk ${this.opts.token}`,
          'content-type': 'application/json',
          // The manifest travels in a header so that the body stays exactly
          // what Splunk expects and an operator can still check the batch.
          'x-antifailure-manifest': JSON.stringify(batch.manifest),
        },
        body,
      },
      'splunk',
    )
  }
}

// ---------------------------------------------------------------------------

export interface EventHubsOptions {
  /** https://<namespace>.servicebus.windows.net/<hub>/messages */
  url: string
  /** A shared access signature. Generated by the caller so that the key never
   *  reaches this package and an operator can use managed identity instead. */
  authorization: string
  fetch: Fetcher
}

/** Azure Event Hubs, which takes a JSON array of records. */
export class EventHubsSink implements Sink {
  private readonly opts: EventHubsOptions

  constructor(opts: EventHubsOptions) {
    this.opts = opts
  }

  name(): string {
    return 'event-hubs'
  }

  async deliver(batch: Batch): Promise<void> {
    await send(
      this.opts.fetch,
      this.opts.url,
      {
        method: 'POST',
        headers: {
          authorization: this.opts.authorization,
          'content-type': 'application/vnd.microsoft.servicebus.json',
          'x-antifailure-manifest': JSON.stringify(batch.manifest),
        },
        body: JSON.stringify(batch.entries.map((entry) => ({ Body: entry }))),
      },
      'event hubs',
    )
  }
}

// ---------------------------------------------------------------------------

export interface ObjectStoreOptions {
  /** Called with the object's key and body. Given rather than implemented,
   *  because S3 and Blob differ in their signing and neither belongs in a
   *  package about audit entries. */
  put: (key: string, body: string, contentType: string) => Promise<void>
  /** Prefix under which objects are written. */
  prefix?: string
}

/**
 * An object store, which is where an auditor usually wants the archive.
 *
 * The manifest is written as a second object beside the batch rather than
 * inside it, so that the batch file is exactly the newline-delimited JSON that
 * every log tool already reads, and the signature is still there for anybody
 * who wants to check it.
 *
 * The key is ordered by sequence and zero padded, so a listing sorts
 * chronologically. A key with a timestamp in it sorts chronologically too and
 * collides when two batches land in the same millisecond.
 */
export class ObjectStoreSink implements Sink {
  private readonly opts: ObjectStoreOptions

  constructor(opts: ObjectStoreOptions) {
    this.opts = opts
  }

  name(): string {
    return 'object-store'
  }

  async deliver(batch: Batch): Promise<void> {
    if (batch.entries.length === 0) return

    const prefix = this.opts.prefix ? `${this.opts.prefix.replace(/\/$/, '')}/` : ''
    const key =
      `${prefix}${batch.manifest.org}/` +
      `${String(batch.manifest.firstSeq).padStart(12, '0')}-` +
      `${String(batch.manifest.lastSeq).padStart(12, '0')}`

    await this.opts.put(
      `${key}.ndjson`,
      batch.entries.map((e) => JSON.stringify(e)).join('\n'),
      'application/x-ndjson',
    )
    await this.opts.put(
      `${key}.manifest.json`,
      JSON.stringify(batch.manifest, null, 2),
      'application/json',
    )
  }
}

// ---------------------------------------------------------------------------

export interface WebhookOptions {
  url: string
  /** Used to sign the body, so the receiver can tell a delivery from this
   *  control plane from anything else that learned the URL. */
  secret: string
  fetch: Fetcher
}

/**
 * A signed webhook, for everything with no adapter.
 *
 * The signature covers the body and a timestamp, and the timestamp is outside
 * the body so a receiver can reject an old delivery without parsing it. A
 * signature over the body alone is replayable forever.
 */
export class WebhookSink implements Sink {
  private readonly opts: WebhookOptions

  constructor(opts: WebhookOptions) {
    this.opts = opts
  }

  name(): string {
    return 'webhook'
  }

  async deliver(batch: Batch): Promise<void> {
    const body = JSON.stringify(batch)
    // Taken from the batch rather than from the clock, so that a redelivery of
    // the same batch carries the same signature and a receiver deduplicating on
    // it sees one delivery.
    const timestamp = batch.entries[0]?.occurredAt ?? ''
    const signature = createHmac('sha256', this.opts.secret)
      .update(`${timestamp}.${body}`)
      .digest('hex')

    await send(
      this.opts.fetch,
      this.opts.url,
      {
        method: 'POST',
        headers: {
          'content-type': 'application/json',
          'x-antifailure-timestamp': timestamp,
          'x-antifailure-signature': `sha256=${signature}`,
        },
        body,
      },
      'webhook',
    )
  }
}

/** Verifies a webhook delivery. Ships so that a receiver can check one without
 *  reimplementing the scheme from a documentation page. */
export function verifyWebhook(
  secret: string,
  timestamp: string,
  body: string,
  signature: string,
): boolean {
  const expected = `sha256=${createHmac('sha256', secret).update(`${timestamp}.${body}`).digest('hex')}`
  if (expected.length !== signature.length) return false
  let diff = 0
  for (let i = 0; i < expected.length; i += 1) {
    diff |= expected.charCodeAt(i) ^ signature.charCodeAt(i)
  }
  return diff === 0
}
