// Command sidebarcheck proves that the documentation sidebar is ordered on
// purpose rather than by accident.
//
// Starlight's autogenerated sidebar sorts a group by each page's
// `sidebar.order` frontmatter and breaks a tie by FILE NAME. That tie break is
// the problem. It is invisible to the person editing the page, because they
// are looking at the title and the file is named something else, and it is
// silent, because two pages sharing a number is not an error anywhere.
//
// Measured when this was written: 27 of the 78 ordered pages shared a number
// with a sibling, so a third of the sidebar was alphabetised by slug while
// reading like a designed order. The damage was not abstract. "Watching a run"
// sat between "The local runtime" and "The Kubernetes runtime" and split the
// pair. "Provider limits" sat between DBLab and Supabase and split the three
// provider pages. The two Next.js guides were separated by Django, Synthesis
// and a page about model keys. "On-call" came before "Standing up production".
// Every one of those was a file name winning an argument nobody had.
//
// So the rule is that a number is a decision, and two pages cannot make the
// same decision. Three assertions, each of which something in this repository
// actually violated:
//
// One, a directory is either fully ordered or fully unordered. A page with no
// order in a group where every sibling has one sorts to the end, which reads
// as a placement and is an omission. reference/schemas is unordered as a
// whole and that is fine.
//
// Two, orders inside a directory are unique integers. Unique because of the
// tie break above. Integers because self-hosting once carried a 3.5 wedged
// between two pages that both claimed 3, which is what somebody does when the
// numbers have run out, and it leaves the next person no room at all.
//
// Three, a nested group's smallest order is larger than every order in its
// parent. This one is not obvious and it bit the change that introduced this
// tool: Starlight places a nested group at the MINIMUM order of its children,
// so renumbering self-hosting/runbooks from 1 lifted the entire runbook group
// above Azure, above Standing up production, above everything. The group's
// position is its children's numbering, so the numbering has to know where the
// group goes.
//
// What this cannot see, said here rather than in a report: it does not know
// whether the order is GOOD. It knows the order was chosen. A page numbered 4
// that belongs at 12 passes, and should, because that is a judgement and this
// is a gate.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// The sidebar is autogenerated per directory under this root, so a directory
// is exactly one sidebar group and the unit every rule below applies to.
const docsRoot = "docs/src/content/docs"

// Where the sidebar is declared. Two groups are listed by hand rather than
// autogenerated, because `autogenerate` labels a nested group with the raw
// directory name and offers no override, so `schemas` and `runbooks` sat in
// lowercase among nine sentence-case labels. A hand-written list is the thing
// that rots, which is why rule four below exists: a page added under either of
// those directories is invisible in the sidebar until somebody remembers, and
// nothing else would have said so.
const sidebarConfig = "docs/astro.config.mjs"

var (
	autogenerateEntry = regexp.MustCompile(`autogenerate:\s*{\s*directory:\s*"([^"]+)"`)
	// A quoted slug with a slash in it, which is how Starlight writes an
	// explicit page entry. The slash is what keeps a label like "Reference"
	// out of the set.
	explicitSlug = regexp.MustCompile(`"([a-z0-9-]+(?:/[a-z0-9.-]+)+)"`)
	orderLine    = regexp.MustCompile(`(?m)^\s+order:\s*(\S+)\s*$`)
	titleLine    = regexp.MustCompile(`(?m)^title:\s*"?(.*?)"?\s*$`)
)

type page struct {
	path  string
	title string
	// order is the raw frontmatter text, kept as written so a fractional or
	// malformed value can be reported in the words the author used.
	order    string
	hasOrder bool
}

func main() {
	flag.Parse()
	root := "."
	if flag.NArg() > 0 {
		root = flag.Arg(0)
	}

	groups, err := collect(filepath.Join(root, docsRoot))
	if err != nil {
		fmt.Fprintln(os.Stderr, "sidebarcheck:", err)
		os.Exit(1)
	}

	problems, pages, groupCount := analyse(groups)

	reach, err := reachability(root, groups)
	if err != nil {
		fmt.Fprintln(os.Stderr, "sidebarcheck:", err)
		os.Exit(1)
	}
	problems = append(problems, reach...)

	if len(problems) > 0 {
		fmt.Fprintf(os.Stderr, "sidebarcheck: %d places where the sidebar order is an accident\n\n", len(problems))
		for _, p := range problems {
			fmt.Fprintln(os.Stderr, "  "+p)
		}
		fmt.Fprintln(os.Stderr)
		os.Exit(1)
	}
	fmt.Printf("sidebarcheck: %d pages in %d sidebar groups, every order unique and deliberate\n", pages, groupCount)
}

func collect(root string) (map[string][]page, error) {
	groups := map[string][]page{}
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || filepath.Ext(path) != ".md" {
			return nil
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return relErr
		}
		dir := filepath.Dir(rel)
		// The root holds one splash page that belongs to no autogenerated
		// group, so it has no order to have an opinion about.
		if dir == "." {
			return nil
		}
		b, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		text := string(b)
		fm := frontmatter(text)
		p := page{path: filepath.ToSlash(rel)}
		if m := titleLine.FindStringSubmatch(fm); m != nil {
			p.title = m[1]
		}
		if m := orderLine.FindStringSubmatch(fm); m != nil {
			p.order, p.hasOrder = m[1], true
		}
		groups[dir] = append(groups[dir], p)
		return nil
	})
	return groups, err
}

// frontmatter returns the YAML block only. Reading the whole file would find an
// `order:` inside a manifest example in a fenced block and report a page that
// declares nothing, which is the false finding this gate cannot afford.
func frontmatter(text string) string {
	if !strings.HasPrefix(text, "---\n") {
		return ""
	}
	rest := text[len("---\n"):]
	if i := strings.Index(rest, "\n---"); i >= 0 {
		return rest[:i]
	}
	return ""
}

func groupName(dir string) string { return filepath.ToSlash(dir) }

// analyse is separate from main so the rules can be exercised against a tree
// built in a test rather than only against the real documentation. A gate
// whose failure has never been observed is not a gate, and the observation has
// to be repeatable rather than something somebody did once by hand.
func analyse(groups map[string][]page) (problems []string, pages, groupCount int) {
	dirs := make([]string, 0, len(groups))
	for d := range groups {
		dirs = append(dirs, d)
	}
	sort.Strings(dirs)

	// min holds each ordered group's smallest order, for the nested-group rule.
	min := map[string]int{}
	max := map[string]int{}

	for _, dir := range dirs {
		ps := groups[dir]
		pages += len(ps)
		ordered, bare := 0, []string{}
		for _, p := range ps {
			if p.hasOrder {
				ordered++
			} else {
				bare = append(bare, p.path)
			}
		}
		if ordered > 0 && len(bare) > 0 {
			for _, b := range bare {
				problems = append(problems, fmt.Sprintf(
					"%s has no sidebar.order while %d of its %d siblings do, so it sorts to the end of %s by omission rather than by choice",
					b, ordered, len(ps), groupName(dir)))
			}
		}
		if ordered == 0 {
			continue
		}

		seen := map[int]string{}
		for _, p := range ps {
			if !p.hasOrder {
				continue
			}
			n, err := strconv.Atoi(p.order)
			if err != nil {
				problems = append(problems, fmt.Sprintf(
					"%s has sidebar.order %q, which is not a whole number. A fraction is what somebody writes when the numbers have run out, and it leaves the next page nowhere to go: renumber the group instead",
					p.path, p.order))
				continue
			}
			if other, dup := seen[n]; dup {
				problems = append(problems, fmt.Sprintf(
					"%s and %s both claim sidebar.order %d in %s, so Starlight breaks the tie on file name and the order you see is alphabetical by slug, not the one either page asked for",
					other, p.path, n, groupName(dir)))
				continue
			}
			seen[n] = p.path
			if v, ok := min[dir]; !ok || n < v {
				min[dir] = n
			}
			if v, ok := max[dir]; !ok || n > v {
				max[dir] = n
			}
		}
	}

	// A nested group renders at the minimum order of its children, so that
	// minimum has to clear everything in the parent or the whole group jumps.
	for _, dir := range dirs {
		parent := filepath.Dir(dir)
		if parent == dir {
			continue
		}
		pMax, ok := max[parent]
		if !ok {
			continue
		}
		cMin, ok := min[dir]
		if !ok {
			continue
		}
		if cMin <= pMax {
			problems = append(problems, fmt.Sprintf(
				"the %s group's smallest sidebar.order is %d and its parent %s goes up to %d. Starlight places a nested group at the smallest order of its children, so %s renders at position %d, above the parent pages, instead of after them. Number the group above %d",
				groupName(dir), cMin, groupName(parent), pMax, groupName(dir), cMin, pMax))
		}
	}

	return problems, pages, len(groups)
}

// reachability checks that every page is in the sidebar exactly once.
//
// A page reaches the sidebar two ways: an `autogenerate` entry whose directory
// contains it, or its own slug written out. Neither is an error and both is:
// listed under an autogenerated directory as well, a page appears twice, which
// is the "one page in two places" defect this tool exists to prevent.
//
// The root index page is deliberately in neither. It is the documentation home,
// reached from the site header, and Starlight has no group for a page that
// belongs to no directory.
func reachability(root string, groups map[string][]page) ([]string, error) {
	b, err := os.ReadFile(filepath.Join(root, sidebarConfig))
	if err != nil {
		// No config is not this tool's business to invent an opinion about.
		return nil, nil
	}
	text := string(b)
	start := strings.Index(text, "sidebar: [")
	if start < 0 {
		return []string{sidebarConfig + " has no `sidebar: [` block, so nothing could be checked against it. " +
			"If the sidebar moved, this rule has to move with it rather than pass quietly"}, nil
	}
	block := text[start:]

	autoDirs := map[string]bool{}
	for _, m := range autogenerateEntry.FindAllStringSubmatch(block, -1) {
		autoDirs[m[1]] = true
	}
	// The autogenerate entries are removed before the explicit slugs are read,
	// because a directory value like "self-hosting/runbooks" is a quoted string
	// with a slash in it and the slug pattern matched it too. That reported the
	// runbooks index as listed twice, which is a finding about the pattern
	// rather than about the sidebar, and a gate that cries wolf once is a gate
	// somebody turns off.
	block = autogenerateEntry.ReplaceAllString(block, "")
	explicit := map[string]int{}
	for _, m := range explicitSlug.FindAllStringSubmatch(block, -1) {
		explicit[m[1]]++
	}

	var problems []string
	known := map[string]bool{}
	for dir, ps := range groups {
		for _, p := range ps {
			slug := strings.TrimSuffix(filepath.ToSlash(p.path), ".md")
			slug = strings.TrimSuffix(slug, "/index")
			known[slug] = true

			auto := false
			for d := range autoDirs {
				if dir == d || strings.HasPrefix(dir+"/", d+"/") {
					auto = true
					break
				}
			}
			n := explicit[slug]
			switch {
			case auto && n > 0:
				problems = append(problems, fmt.Sprintf(
					"%s is inside the autogenerated directory %q AND written out in %s, so it appears in the sidebar twice",
					p.path, dirOfAuto(autoDirs, dir), sidebarConfig))
			case !auto && n == 0:
				problems = append(problems, fmt.Sprintf(
					"%s is in no sidebar group. %s lists %s by hand and this page is not in the list, so a reader can only reach it by search",
					p.path, sidebarConfig, groupName(dir)))
			case !auto && n > 1:
				problems = append(problems, fmt.Sprintf(
					"%s is written out %d times in %s, so it appears in the sidebar more than once", p.path, n, sidebarConfig))
			}
		}
	}
	// A hand-listed group renders in the order of the ARRAY, so its pages'
	// sidebar.order is inert there. Two descriptions of one thing is the shape
	// this repository keeps finding defects in, and the inert one is the
	// dangerous half: somebody renumbers the frontmatter, nothing moves, and
	// they conclude the sidebar is broken. So the two have to agree, and the
	// frontmatter stays meaningful as the record of intent and as what would
	// render if the group ever went back to autogenerate.
	problems = append(problems, handListedOrderAgrees(block, groups)...)

	// A slug written out that names no page is a dead sidebar entry.
	names := make([]string, 0, len(explicit))
	for slug := range explicit {
		names = append(names, slug)
	}
	sort.Strings(names)
	for _, slug := range names {
		if !known[slug] {
			problems = append(problems, fmt.Sprintf(
				"%s names %q in the sidebar and no such page exists", sidebarConfig, slug))
		}
	}
	sort.Strings(problems)
	return problems, nil
}

func dirOfAuto(autoDirs map[string]bool, dir string) string {
	for d := range autoDirs {
		if dir == d || strings.HasPrefix(dir+"/", d+"/") {
			return d
		}
	}
	return dir
}

// handListedOrderAgrees checks a hand-listed group against its frontmatter.
func handListedOrderAgrees(block string, groups map[string][]page) []string {
	// The slugs in the order the config writes them, which is the order that
	// actually renders.
	var listed []string
	for _, m := range explicitSlug.FindAllStringSubmatch(block, -1) {
		listed = append(listed, m[1])
	}

	byDir := map[string][]string{}
	for _, slug := range listed {
		byDir[filepath.Dir(slug)] = append(byDir[filepath.Dir(slug)], slug)
	}

	orderOf := map[string]int{}
	for dir, ps := range groups {
		for _, p := range ps {
			if !p.hasOrder {
				continue
			}
			n, err := strconv.Atoi(p.order)
			if err != nil {
				continue
			}
			slug := strings.TrimSuffix(filepath.ToSlash(p.path), ".md")
			slug = strings.TrimSuffix(slug, "/index")
			_ = dir
			orderOf[slug] = n
		}
	}

	var problems []string
	dirs := make([]string, 0, len(byDir))
	for d := range byDir {
		dirs = append(dirs, d)
	}
	sort.Strings(dirs)
	for _, dir := range dirs {
		slugs := byDir[dir]
		for i := 1; i < len(slugs); i++ {
			prev, cur := slugs[i-1], slugs[i]
			pn, pok := orderOf[prev]
			cn, cok := orderOf[cur]
			if !pok || !cok {
				continue
			}
			if pn > cn {
				problems = append(problems, fmt.Sprintf(
					"%s lists %q before %q and their sidebar.order says the opposite, %d then %d. "+
						"The array is what renders, so the frontmatter is describing an order nobody sees",
					sidebarConfig, prev, cur, pn, cn))
			}
		}
	}
	return problems
}
