{{- include "cp.validate" . -}}
{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cp.fullname" . }}-database
  labels: {{- include "cp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.secretKeys.url }}: {{ .Values.database.url | quote }}
  {{- if .Values.database.migrationUrl }}
  {{ .Values.database.secretKeys.migrationUrl }}: {{ .Values.database.migrationUrl | quote }}
  {{- end }}
{{- end }}
---
{{- if not .Values.github.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cp.fullname" . }}-github
  labels: {{- include "cp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.github.secretKeys.clientId }}: {{ .Values.github.clientId | quote }}
  {{ .Values.github.secretKeys.clientSecret }}: {{ .Values.github.clientSecret | quote }}
  {{ .Values.github.secretKeys.redirectUri }}: {{ .Values.github.redirectUri | quote }}
{{- end }}
