// Package docs serves this build's own documentation to a caller that has to
// read it inside a budget.
//
// The problem it exists for is not "the documentation is not available". It is
// that 89 pages and 1.1 MB of Markdown is far more than any agent should pull
// into a conversation, so a tool that answers a narrow question with a whole
// page is worse than no tool at all: it costs the caller the room it needed to
// act on the answer. Everything here is built around that. A search returns
// excerpts and never pages, a listing costs a few hundred tokens rather than
// many thousands, a page is read by section, and every answer states what it
// did NOT return, because a silent truncation is a reader believing it has
// seen everything.
//
// The pages themselves are in pages.gen.go, generated by tools/docsembed from
// docs/src/content/docs. See that command for why they are embedded rather
// than read from disk: the MCP server is bound to the CALLER'S checkout, which
// is their application and has no copy of this repository's documentation in
// it.
package docs

import (
	"fmt"
	"math"
	"sort"
	"strings"
	"sync"
	"unicode"
)

// A Page is one documentation page as it ships.
type Page struct {
	// Path is the page's path under docs/src/content/docs, such as
	// "concepts/goldens.md". It is the identifier a caller passes back.
	Path string
	// Section is the top level directory, such as "concepts". The root
	// index.md has no section and reports "index".
	Section string
	// Title and Description come from the page's own frontmatter, which every
	// page on this site carries because Starlight requires a title.
	Title       string
	Description string
	// Body is the page with its frontmatter removed, so an offset into it is
	// an offset into the prose a reader sees.
	Body string
	// Lines is Body split on newlines, kept because every excerpt in this
	// package is measured in lines rather than in bytes.
	Lines []string
	// terms is every word on the page, for deciding how common a word is
	// across the corpus. Held per page rather than as one global count,
	// because a word's weight is how many PAGES carry it and a total that
	// counted a page twice would make a rare word look common.
	terms map[string]int
	// Headings are the page's own headings in document order.
	Headings []Heading
}

// A Heading is one section of a page.
type Heading struct {
	// Level is the number of leading hashes: 2 for "## Goldens".
	Level int
	// Text is the heading as written, with its Markdown left alone.
	Text string
	// Anchor is the fragment the site serves it at, which is also what a
	// caller passes to read just this section.
	Anchor string
	// Trail is the heading path from the top of the page, such as
	// "Bounded output > Why a page is not returned". It is what tells a
	// reader where an excerpt came from without returning the page.
	Trail string
	// FirstLine is the heading's own line, 1 based into Lines. LastLine is
	// the last line belonging to this section, which is the line before the
	// next heading at this level or above.
	FirstLine, LastLine int
}

// index is the parsed corpus, built once.
type index struct {
	pages    []*Page
	byPath   map[string]*Page
	sections []string
	// pagesWithTerm is how many pages contain each term, which is what makes
	// a query's common words cost almost nothing. See scoreOf.
	pagesWithTerm map[string]int
}

var (
	loadOnce sync.Once
	loaded   *index
)

// load parses the embedded pages once.
//
// Once rather than per call, because parsing 1.1 MB of Markdown on every
// search would be paid by the caller in latency for no benefit.
//
// It is NOT deferred until somebody asks a question, and saying so is the
// honest version: the MCP server publishes the real section names in the
// enum of its documentation tools, so building those schemas at startup
// parses the corpus at startup, for every session, whether or not anybody
// asks anything. That is the trade taken deliberately. A published enum a
// caller can read is worth more than the tens of milliseconds and few
// megabytes it costs, and the alternative, a hand written list of section
// names, is a second description of the directory layout able to disagree
// with it.
func load() *index {
	loadOnce.Do(func() { loaded = build(Pages) })
	return loaded
}

// build parses a set of pages. Separate from load so a test can build an
// index from pages it wrote itself.
func build(pages map[string]string) *index {
	ix := &index{
		byPath:        make(map[string]*Page, len(pages)),
		pagesWithTerm: map[string]int{},
	}
	paths := make([]string, 0, len(pages))
	for path := range pages {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	seenSection := map[string]bool{}
	for _, path := range paths {
		page := parse(path, pages[path])
		ix.pages = append(ix.pages, page)
		ix.byPath[path] = page
		if !seenSection[page.Section] {
			seenSection[page.Section] = true
			ix.sections = append(ix.sections, page.Section)
		}
		page.terms = termsIn(page.Title + " " + page.Description + " " + page.Body)
		for term := range page.terms {
			ix.pagesWithTerm[term]++
		}
	}
	sort.Strings(ix.sections)
	return ix
}

// PageCount is how many pages this build ships.
func PageCount() int { return len(load().pages) }

// Sections are the top level groups, in order.
func Sections() []string { return append([]string(nil), load().sections...) }

// The package level entry points are one line each over the index they read,
// so that a test can build an index from pages it wrote itself and exercise
// exactly the same code the shipped corpus goes through. A search that is only
// ever tested against 92 real pages is a search whose behaviour at the edges
// nobody can arrange.

// Listing is one page in a table of contents.
type Listing struct {
	Path        string
	Section     string
	Title       string
	Description string
	Headings    int
	Chars       int
}

// List returns the table of contents, narrowed to one section when section is
// not empty. An unknown section returns nothing, and the caller says so.
func List(section string) []Listing { return load().list(section) }

func (ix *index) list(section string) []Listing {
	out := []Listing{}
	for _, p := range ix.pages {
		if section != "" && p.Section != section {
			continue
		}
		out = append(out, Listing{
			Path: p.Path, Section: p.Section, Title: p.Title,
			Description: p.Description, Headings: len(p.Headings), Chars: len(p.Body),
		})
	}
	return out
}

// Lookup finds a page by path, tolerantly.
//
// Tolerant on purpose, and only here. A caller that read "concepts/goldens.md"
// out of a search result passes it back exactly; a caller that inferred a path
// from a URL passes "/docs/concepts/goldens" or "concepts/goldens", and
// refusing those would spend a round trip teaching an agent a file extension.
// Nothing is guessed: each candidate is an exact key or it is not.
func Lookup(path string) (*Page, bool) { return load().lookup(path) }

func (ix *index) lookup(path string) (*Page, bool) {
	cleaned := strings.TrimSpace(path)
	cleaned = strings.TrimPrefix(cleaned, "/")
	cleaned = strings.TrimPrefix(cleaned, "docs/")
	cleaned = strings.TrimSuffix(cleaned, "/")
	for _, candidate := range []string{
		cleaned,
		cleaned + ".md",
		strings.TrimSuffix(cleaned, ".md") + "/index.md",
	} {
		if p, ok := ix.byPath[candidate]; ok {
			return p, true
		}
	}
	return nil, false
}

// Near returns the paths closest to one that was not found, so a refusal can
// name what the caller probably meant.
func Near(path string, limit int) []string { return load().near(path, limit) }

func (ix *index) near(path string, limit int) []string {
	wanted := termsIn(strings.ReplaceAll(strings.TrimSuffix(path, ".md"), "/", " "))
	type scored struct {
		path  string
		score int
	}
	var ranked []scored
	for _, p := range ix.pages {
		score := 0
		for term := range termsIn(strings.ReplaceAll(strings.TrimSuffix(p.Path, ".md"), "/", " ")) {
			if _, wants := wanted[term]; wants {
				score += 10
			}
		}
		for term := range wanted {
			if strings.Contains(p.Path, term) {
				score++
			}
		}
		if score > 0 {
			ranked = append(ranked, scored{p.Path, score})
		}
	}
	sort.SliceStable(ranked, func(i, j int) bool { return ranked[i].score > ranked[j].score })
	out := []string{}
	for _, r := range ranked {
		if len(out) >= limit {
			break
		}
		out = append(out, r.path)
	}
	return out
}

// FindHeading returns a page's section by anchor or by the heading's own text.
func (p *Page) FindHeading(anchor string) (*Heading, bool) {
	wanted := slug(anchor)
	for i := range p.Headings {
		if p.Headings[i].Anchor == wanted {
			return &p.Headings[i], true
		}
	}
	return nil, false
}

// Anchors lists a page's section anchors, which is what a caller needs to ask
// for one of them.
func (p *Page) Anchors() []string {
	out := make([]string, 0, len(p.Headings))
	for _, h := range p.Headings {
		out = append(out, h.Anchor)
	}
	return out
}

// Text returns the lines from first to last inclusive, both 1 based.
func (p *Page) Text(first, last int) string {
	if first < 1 {
		first = 1
	}
	if last > len(p.Lines) {
		last = len(p.Lines)
	}
	if first > last {
		return ""
	}
	return strings.Join(p.Lines[first-1:last], "\n")
}

// -----------------------------------------------------------------------
// parsing
// -----------------------------------------------------------------------

// parse reads one page into its frontmatter, its body and its headings.
func parse(path, raw string) *Page {
	front, body := splitFrontmatter(raw)
	page := &Page{
		Path:        path,
		Section:     sectionOf(path),
		Title:       frontmatterField(front, "title"),
		Description: frontmatterField(front, "description"),
		Body:        body,
		Lines:       strings.Split(body, "\n"),
	}
	if page.Title == "" {
		// Every page on this site has one, because Starlight refuses a page
		// without it. Falling back to the path rather than to an empty string
		// keeps a listing readable if that ever stops being true.
		page.Title = path
	}
	page.Headings = headingsIn(page.Lines, page.Title)
	return page
}

// splitFrontmatter removes the leading YAML block and returns both halves.
func splitFrontmatter(raw string) (front, body string) {
	if !strings.HasPrefix(raw, "---\n") {
		return "", raw
	}
	rest := raw[len("---\n"):]
	end := strings.Index(rest, "\n---\n")
	if end < 0 {
		return "", raw
	}
	return rest[:end], strings.TrimLeft(rest[end+len("\n---\n"):], "\n")
}

// frontmatterField reads one top level scalar out of the frontmatter.
//
// A line scan rather than a YAML parser, and the limit is stated rather than
// discovered later: it reads top level scalars only, so a nested
// "sidebar.order" is invisible here. Two fields are wanted, both are top level
// on every page of this site, and pulling a YAML dependency into the engine to
// read them would be a larger decision than the fields are worth.
func frontmatterField(front, name string) string {
	for _, line := range strings.Split(front, "\n") {
		if !strings.HasPrefix(line, name+":") {
			continue
		}
		value := strings.TrimSpace(strings.TrimPrefix(line, name+":"))
		value = strings.Trim(value, `"'`)
		return value
	}
	return ""
}

// sectionOf is the top level directory a page lives in.
func sectionOf(path string) string {
	if dir, _, found := strings.Cut(path, "/"); found {
		return dir
	}
	return "index"
}

// headingsIn finds the headings of a body, ignoring the ones inside fenced
// code blocks.
//
// The fence tracking is not fussiness. Several pages here show shell sessions
// whose comments begin with a hash, and reading those as headings would build
// a table of contents out of somebody's example script.
func headingsIn(lines []string, title string) []Heading {
	// openHeading is an ancestor of whatever is being read now.
	type openHeading struct {
		level int
		text  string
		at    int
	}
	var out []Heading
	var stack []openHeading
	used := map[string]int{}
	fence := ""

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		switch {
		case fence != "":
			if strings.HasPrefix(trimmed, fence) {
				fence = ""
			}
			continue
		case strings.HasPrefix(trimmed, "```"):
			fence = "```"
			continue
		case strings.HasPrefix(trimmed, "~~~"):
			fence = "~~~"
			continue
		case !strings.HasPrefix(trimmed, "#"):
			continue
		}

		level := 0
		for level < len(trimmed) && trimmed[level] == '#' {
			level++
		}
		if level > 6 || level >= len(trimmed) || trimmed[level] != ' ' {
			// A hash run with no space after it is not a heading. It is a
			// comment, or a fragment somebody wrote in prose.
			continue
		}
		text := strings.TrimSpace(trimmed[level:])
		if text == "" {
			continue
		}

		// Every heading at this level or deeper is closed by this one. Its
		// section ends on the line before, and it stops being an ancestor.
		for len(stack) > 0 && stack[len(stack)-1].level >= level {
			out[stack[len(stack)-1].at].LastLine = i
			stack = stack[:len(stack)-1]
		}

		anchor := slug(text)
		used[anchor]++
		if used[anchor] > 1 {
			// The site's own slugger disambiguates a repeated heading the
			// same way, so an anchor here is an anchor there.
			anchor = fmt.Sprintf("%s-%d", anchor, used[anchor]-1)
		}
		trail := make([]string, 0, len(stack)+2)
		trail = append(trail, title)
		for _, ancestor := range stack {
			trail = append(trail, ancestor.text)
		}
		trail = append(trail, text)

		out = append(out, Heading{
			Level: level, Text: text, Anchor: anchor,
			Trail: strings.Join(trail, " > "),
			// Left open. Whatever closes it writes the real value, and the
			// sweep below closes the ones nothing did.
			FirstLine: i + 1, LastLine: 0,
		})
		stack = append(stack, openHeading{level: level, text: text, at: len(out) - 1})
	}
	// Whatever is still open runs to the end of the page.
	for i := range out {
		if out[i].LastLine == 0 {
			out[i].LastLine = len(lines)
		}
	}
	return out
}

// slug renders a heading as the fragment the site serves it at.
//
// It is github-slugger's rule, which is what Starlight uses: lowercase, drop
// everything that is not a letter, a digit or an underscore, and turn spaces
// into hyphens. The underscore SURVIVES, and that is not a detail here: half
// the headings in the MCP reference are tool names like
// rehearse_migration_safety, and an anchor that hyphenated them would be an
// anchor the site does not serve and this package cannot find.
func slug(text string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(strings.TrimSpace(text)) {
		switch {
		case unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_':
			b.WriteRune(r)
		case r == ' ' || r == '-':
			b.WriteRune('-')
		}
	}
	return strings.Trim(b.String(), "-")
}

// termsIn is the tokenizer both the index and a query use.
//
// One function for both, because two tokenizers is how a term that is indexed
// one way and looked up another silently matches nothing.
func termsIn(s string) map[string]int {
	out := map[string]int{}
	field := strings.Builder{}
	flush := func() {
		if field.Len() >= 2 {
			out[field.String()]++
		}
		field.Reset()
	}
	for _, r := range strings.ToLower(s) {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_' {
			field.WriteRune(r)
			continue
		}
		flush()
	}
	flush()
	return out
}

// -----------------------------------------------------------------------
// search
// -----------------------------------------------------------------------

// Query is one search, with the budget the caller is willing to spend.
type Query struct {
	// Text is what the caller asked, in their own words.
	Text string
	// Section narrows to one top level group. Empty searches all of them.
	Section string
	// MaxResults and MaxChars are the caller's budget. MaxChars is the sum of
	// every excerpt in the answer, and it is honoured rather than advertised:
	// excerpts are shortened and then dropped to stay inside it, and whatever
	// was dropped is named.
	MaxResults int
	MaxChars   int
}

// A Hit is one page's best matching section, with the lines around the match.
type Hit struct {
	Path  string
	Title string
	// Trail is the heading path the excerpt came from, or the page title when
	// the match was above the first heading.
	Trail string
	// Anchor is what to pass to read this section, empty when the match was
	// above the first heading.
	Anchor string
	// FirstLine and LastLine locate the excerpt in the page.
	FirstLine, LastLine int
	// Excerpt is the lines around the match, bounded.
	Excerpt string
	// Clipped says the excerpt itself was cut to fit the budget.
	Clipped bool
	// OtherSections is how many further sections of this same page matched
	// and were not returned, so a caller knows the page has more to say.
	OtherSections int
	score         float64
}

// Results is what a search answers, including everything it did not answer.
type Results struct {
	Terms []string
	Hits  []Hit
	// PagesMatched is how many pages matched, before any budget was applied.
	PagesMatched int
	// SectionsMatched is how many sections across all of them matched.
	SectionsMatched int
	// PagesNotShown names the pages that matched and were left out, bounded
	// itself, with NotShownTotal carrying the true count.
	PagesNotShown []string
	NotShownTotal int
	// CharsUsed is the size of the excerpts actually returned, against the
	// budget that was asked for.
	CharsUsed, CharsBudget int
	// Truncated says plainly that something was withheld, whether a page was
	// dropped or an excerpt was cut.
	Truncated bool
}

// contextLines is how many lines either side of a match an excerpt carries.
//
// Three, measured against the real corpus rather than chosen: two cuts the
// header off a Markdown table and leaves a row with no column names, which is
// worse than not answering. Fixed rather than a parameter, because the knob a
// caller needs is the budget, and a second one that also changes the size
// makes the two able to disagree about which of them was honoured.
const contextLines = 3

// minExcerptChars is the smallest excerpt worth returning.
//
// Below this an excerpt is a fragment of a sentence, which is the shape of
// answer that reads as complete and is not. A budget too small for one of
// these returns no excerpt and says so, rather than half a line.
const minExcerptChars = 120

// maxPagesNamedAsNotShown bounds the list of what was left out, so that the
// note about truncation cannot itself become the thing that fills the answer.
const maxPagesNamedAsNotShown = 20

// Search finds the sections that answer a question and returns excerpts of
// them, inside the caller's budget.
func Search(q Query) Results { return load().search(q) }

func (ix *index) search(q Query) Results {
	terms := termsIn(q.Text)
	query := ix.compile(q.Text)
	out := Results{Terms: query.Terms, Hits: []Hit{}, PagesNotShown: []string{},
		CharsBudget: q.MaxChars}
	if len(terms) == 0 {
		return out
	}

	var ranked []Hit
	for _, p := range ix.pages {
		if q.Section != "" && p.Section != q.Section {
			continue
		}
		best, others := bestSection(query, p, terms)
		if best == nil {
			continue
		}
		best.OtherSections = others
		ranked = append(ranked, *best)
		out.SectionsMatched += others + 1
	}
	sort.SliceStable(ranked, func(i, j int) bool { return ranked[i].score > ranked[j].score })
	out.PagesMatched = len(ranked)

	used := 0
	for i := range ranked {
		hit := ranked[i]
		// What this hit may spend: an even share of what is LEFT, over the
		// slots still open. An even share of the whole budget instead would
		// cut the last excerpt while the budget still had room in it, which
		// is a truncation the caller paid for and did not need.
		//
		// A caller that lowers max_chars still gets shorter excerpts AND
		// fewer of them, which is what "less content" has to mean for the
		// budget to be worth asking for.
		perHit := q.MaxChars - used
		if slots := q.MaxResults - len(out.Hits); slots > 1 {
			perHit /= slots
		}
		if perHit < minExcerptChars {
			perHit = minExcerptChars
		}
		if len(out.Hits) >= q.MaxResults {
			out.PagesNotShown = appendNotShown(out.PagesNotShown, hit.Path)
			out.NotShownTotal++
			continue
		}
		excerpt, clipped := clipExcerpt(hit.Excerpt, perHit)
		if used+len(excerpt) > q.MaxChars {
			// The budget is spent. Everything from here on is named rather
			// than shortened further, because an excerpt below the floor is
			// not an answer.
			out.PagesNotShown = appendNotShown(out.PagesNotShown, hit.Path)
			out.NotShownTotal++
			continue
		}
		hit.Excerpt, hit.Clipped = excerpt, clipped
		used += len(excerpt)
		out.Hits = append(out.Hits, hit)
	}
	out.CharsUsed = used
	out.Truncated = out.NotShownTotal > 0
	for _, h := range out.Hits {
		if h.Clipped {
			out.Truncated = true
		}
	}
	return out
}

// appendNotShown adds a path to the bounded list of what was left out.
func appendNotShown(list []string, path string) []string {
	if len(list) >= maxPagesNamedAsNotShown {
		return list
	}
	return append(list, path)
}

// headingBonus is what a query word in the heading itself is worth, on top of
// the same word appearing in the section's text.
//
// A section whose heading carries the word is usually the answer, and without
// this the ranking is decided by how long a section is: a passing mention in
// four hundred lines outweighs a heading that names the thing.
const headingBonus = 3

// titleBonus is what a query word in the page's title or description is
// worth. It applies to the whole page rather than to one section of it.
const titleBonus = 4

// bestSection scores every section of a page and returns the best one, plus
// how many others matched.
func bestSection(q compiled, p *Page, terms map[string]int) (*Hit, int) {
	type candidate struct {
		hit   Hit
		score float64
	}
	var best *candidate
	matched := 0

	consider := func(trail, anchor, heading string, first, last int) {
		score, isHit := q.matches(p.Text(first, last))
		if !isHit {
			return
		}
		if heading != "" {
			headingScore, _ := q.score(heading)
			score += headingBonus * headingScore
		}
		matched++
		if best != nil && score <= best.score {
			return
		}
		firstLine, lastLine, excerpt := excerptAround(p, terms, first, last)
		best = &candidate{score: score, hit: Hit{
			Path: p.Path, Title: p.Title, Trail: trail, Anchor: anchor,
			FirstLine: firstLine, LastLine: lastLine, Excerpt: excerpt, score: score,
		}}
	}

	// The lead, meaning everything above the first heading. It is where a page
	// says what it is, so it is often the best answer on the page.
	lead := len(p.Lines)
	if len(p.Headings) > 0 {
		lead = p.Headings[0].FirstLine - 1
	}
	if lead > 0 {
		consider(p.Title, "", p.Title, 1, lead)
	}
	for _, h := range p.Headings {
		consider(h.Trail, h.Anchor, h.Text, h.FirstLine, h.LastLine)
	}
	if best == nil {
		return nil, 0
	}
	// The page's own title and description count for the whole page rather
	// than for one section of it, so they are added after the sections have
	// been compared against each other.
	pageScore, _ := q.score(p.Title + " " + p.Description)
	best.hit.score += titleBonus * pageScore
	return &best.hit, matched - 1
}

// compiled is one query, resolved against the corpus before anything is
// scored.
type compiled struct {
	// Terms are the words as the caller wrote them, for reporting.
	Terms []string
	// weight is every indexed word this query can match, mapped to what a
	// match is worth. A word's weight is the inverse of how many pages carry
	// it, which is what makes "what does stance mean" find the stance pages
	// rather than every page containing the word "does".
	//
	// There is no stopword list, and that is deliberate: a hand written list
	// of English function words would be wrong for a corpus where "load",
	// "run" and "check" are both ordinary words and product nouns, and it
	// would have to be maintained by somebody who remembered it existed.
	weight map[string]float64
	// selective is the subset of those words that appears in fewer than half
	// the pages. A hit has to match at least one of them.
	//
	// Without this every page in the corpus "matches" a question phrased as a
	// question, because "what" and "is" are in all of them, and an answer
	// saying 92 pages matched and 3 are shown is a truthful sentence that
	// tells the caller nothing. A word carried by half the corpus is not
	// evidence that a page is about anything.
	selective map[string]bool
	// anySelective says the query had a selective word at all. A query made
	// entirely of common words still gets an answer, ranked by the little the
	// words are worth, rather than nothing.
	anySelective bool
}

// nearVariantChars is how much longer a word may be than the query word it
// answers.
//
// Two characters, which covers the plural and the past tense: stance and
// stances, branch and branched, golden and goldens. It is a deliberately
// cheap stand in for a stemmer. The cost of getting it wrong is a slightly
// worse ranking, never a wrong answer, because the excerpt returned is the
// text itself.
const nearVariantChars = 2

// compile resolves a query against the corpus.
func (ix *index) compile(text string) compiled {
	asked := termsIn(text)
	out := compiled{
		Terms: sortedTerms(asked), weight: map[string]float64{},
		selective: map[string]bool{},
	}
	total := float64(len(ix.pages))
	if total < 1 {
		return out
	}
	for term := range asked {
		variants := ix.variantsOf(term)
		// How many PAGES this word could match at all, counting a page once
		// however many of its variants that page carries. Summing the per
		// variant counts instead would double count the pages carrying both
		// "stance" and "stances", which is most of the pages that are about
		// stances, and would make the word look common exactly where it is
		// most selective.
		pages := float64(ix.pagesCarryingAny(variants))
		if pages < 1 {
			continue
		}
		selective := pages*2 <= total
		if selective {
			out.anySelective = true
		}
		weight := math.Log(1 + total/pages)
		for _, v := range variants {
			// A word reached by two query words keeps the larger weight.
			if weight > out.weight[v] {
				out.weight[v] = weight
			}
			out.selective[v] = out.selective[v] || selective
		}
	}
	return out
}

// variantsOf returns the indexed words a query word answers: itself, the
// slightly longer forms of it, and the slightly shorter word it is a form of.
func (ix *index) variantsOf(term string) []string {
	var out []string
	for indexed := range ix.pagesWithTerm {
		switch {
		case indexed == term:
		case strings.HasPrefix(indexed, term) && len(indexed)-len(term) <= nearVariantChars:
		case strings.HasPrefix(term, indexed) && len(term)-len(indexed) <= nearVariantChars:
		default:
			continue
		}
		out = append(out, indexed)
	}
	sort.Strings(out)
	return out
}

// pagesCarryingAny counts the pages holding at least one of these words.
func (ix *index) pagesCarryingAny(variants []string) int {
	count := 0
	for _, p := range ix.pages {
		for _, v := range variants {
			if _, present := p.terms[v]; present {
				count++
				break
			}
		}
	}
	return count
}

// score weighs the query against a piece of text.
//
// The second return says whether a selective word matched, which is what
// separates a page that is about the question from a page that merely
// contains the word "is".
func (c compiled) score(text string) (float64, bool) {
	if strings.TrimSpace(text) == "" {
		return 0, false
	}
	score, selective := 0.0, false
	for word, hits := range termsIn(text) {
		weight, known := c.weight[word]
		if !known {
			continue
		}
		if c.selective[word] {
			selective = true
		}
		// Occurrences count with a sharply diminishing return: a section that
		// says the word five times is a better answer than one that says it
		// once, and not five times better.
		score += weight * (1 + math.Log(float64(hits)))
	}
	return score, selective
}

// matches reports whether a piece of text is a hit at all.
func (c compiled) matches(text string) (float64, bool) {
	score, selective := c.score(text)
	if score <= 0 {
		return 0, false
	}
	if c.anySelective && !selective {
		return score, false
	}
	return score, true
}

// excerptAround finds the densest run of lines inside a section and returns
// it with its context.
func excerptAround(p *Page, terms map[string]int, first, last int) (int, int, string) {
	bestLine, bestHits := first, -1
	for line := first; line <= last && line <= len(p.Lines); line++ {
		found := termsIn(p.Lines[line-1])
		hits := 0
		for term := range terms {
			hits += found[term]
		}
		if hits > bestHits {
			bestLine, bestHits = line, hits
		}
	}
	from, to := bestLine-contextLines, bestLine+contextLines
	if from < first {
		from = first
	}
	if to > last {
		to = last
	}
	return from, to, p.Text(from, to)
}

// CutMarker is the one sentence a cut leaves behind.
//
// A silently cut string is a string a reader believes is complete, and half a
// page read as a whole one is how a truncation becomes a wrong answer.
//
// Exported because the MCP tool that renders these results bounds its own
// output and has to leave room for exactly this, and a second copy of the
// sentence over there would be two descriptions of one thing, able to
// disagree the first time either is edited.
const CutMarker = "[cut here to fit the character budget]"

// clipExcerpt cuts text to the budget and says that it did.
//
// It cuts on a line boundary where it can, because half a line of Markdown is
// harder to read than one line fewer, and marks the cut either way.
func clipExcerpt(text string, max int) (string, bool) {
	if len(text) <= max {
		return text, false
	}
	cut := max
	if nl := strings.LastIndexByte(text[:max], '\n'); nl > max/2 {
		cut = nl
	}
	for cut > 0 && text[cut]&0xC0 == 0x80 {
		cut--
	}
	return strings.TrimRight(text[:cut], " \n") + "\n" + CutMarker, true
}

func sortedTerms(terms map[string]int) []string {
	out := make([]string, 0, len(terms))
	for t := range terms {
		out = append(out, t)
	}
	sort.Strings(out)
	return out
}

// -----------------------------------------------------------------------
// reading one page
// -----------------------------------------------------------------------

// Reading is one bounded read, and an account of what it left out.
type Reading struct {
	Path        string
	Title       string
	Description string
	// Trail is the section that was read, or the page title for a whole page.
	Trail string
	// Anchor is the section that was read, empty for a whole page.
	Anchor string
	// Text is what was returned.
	Text                string
	FirstLine, LastLine int
	// TotalChars is the size of what was asked for, so a caller can see how
	// much of it arrived. ReturnedChars is what it got.
	TotalChars, ReturnedChars int
	Truncated                 bool
	// SectionsNotReturned names the anchors past the cut, which is what turns
	// a truncation into a next call rather than a dead end.
	SectionsNotReturned []string
	// NotReturnedChars is how much of what was asked for was withheld.
	NotReturnedChars int
	// Anchors are every section of the page, so one call can be followed by
	// an exact one.
	Anchors []string
}

// Read returns a page, or one of its sections, bounded to maxChars.
//
// The page and the heading are resolved by the caller rather than here, so
// that a path nobody ships and a section a page does not have are two
// different refusals. Reporting either as the other sends an agent to fix the
// wrong half of its call.
func Read(page *Page, section *Heading, maxChars int) *Reading {
	first, last := 1, len(page.Lines)
	trail, anchor := page.Title, ""
	if section != nil {
		first, last = section.FirstLine, section.LastLine
		trail, anchor = section.Trail, section.Anchor
	}

	full := page.Text(first, last)
	out := &Reading{
		Path: page.Path, Title: page.Title, Description: page.Description,
		Trail: trail, Anchor: anchor, Text: full,
		FirstLine: first, LastLine: last, TotalChars: len(full),
		Anchors: page.Anchors(), SectionsNotReturned: []string{},
	}
	if len(full) > maxChars {
		out.Truncated = true
		out.Text, _ = clipExcerpt(full, maxChars)
		// The last line actually returned, so LastLine is not a claim about
		// text nobody was given.
		out.LastLine = first + strings.Count(out.Text, "\n") - 1
		for _, h := range page.Headings {
			if h.FirstLine > out.LastLine && h.FirstLine <= last {
				out.SectionsNotReturned = append(out.SectionsNotReturned, h.Anchor)
			}
		}
	}
	out.ReturnedChars = len(out.Text)
	out.NotReturnedChars = out.TotalChars - len(strings.TrimSuffix(out.Text, "\n"+CutMarker))
	if out.NotReturnedChars < 0 {
		out.NotReturnedChars = 0
	}
	return out
}
