package webhook_test

import (
	"bytes"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/antifailure/antifailure/engine/internal/webhook"
)

// The point of this package is that an application which verifies signatures,
// which is every application that should, accepts what it produces. That claim
// was only ever checked against Verify in this same package, which is the
// signer checking its own arithmetic: it would pass just as well if both sides
// signed the wrong bytes.
//
// The control plane is such an application. Its Stripe webhook decides who has
// paid, it verifies the HMAC over the raw body before parsing anything, and it
// is written in TypeScript. So this emits real signed events and
// web/apps/api/test/billing.test.ts proves the control plane's own verifier
// accepts them, which is the claim actually worth making.
//
// Regenerate with 'go test ./internal/webhook -update-vectors'.

var updateVectors = flag.Bool("update-vectors", false,
	"rewrite schemas/webhook-vectors.json from the current implementation")

type vectorFile struct {
	Note   string        `json:"note"`
	Events []vectorEvent `json:"events"`
}

type vectorEvent struct {
	// Why names what the case is here to pin down.
	Why      string `json:"why"`
	Provider string `json:"provider"`
	Type     string `json:"type"`
	Secret   string `json:"secret"`
	// SignedAt is the instant the signature was produced, in seconds. A
	// verifier compares it against its own clock, so a consumer has to know it
	// rather than guess.
	SignedAt int64             `json:"signed_at"`
	Body     string            `json:"body"`
	Headers  map[string]string `json:"headers"`
}

// The instant everything is signed at. Fixed, because a corpus signed at the
// real time would differ on every run and could never be checked in.
var signedAt = time.Unix(1767225600, 0).UTC()

func buildWebhookVectors(t *testing.T) vectorFile {
	t.Helper()
	secret := webhook.SecretFor("env-vectors", "stripe")

	cases := []struct {
		why       string
		event     string
		overrides map[string]any
	}{
		{
			why:   "the event a purchase produces, which is what a billing integration acts on",
			event: "customer.subscription.created",
			overrides: map[string]any{
				"id": "sub_vectors01", "customer": "cus_vectors01",
			},
		},
		{
			why:   "a plan change, carrying the same subscription",
			event: "customer.subscription.updated",
			overrides: map[string]any{
				"id": "sub_vectors01", "customer": "cus_vectors01",
			},
		},
		{
			why:   "the end of a subscription, which is what drops an organization's plan",
			event: "customer.subscription.deleted",
			overrides: map[string]any{
				"id": "sub_vectors01", "customer": "cus_vectors01",
			},
		},
		{
			why:   "a payment, which is what an invoice row is written from",
			event: "invoice.paid",
			overrides: map[string]any{
				"id": "in_vectors01", "customer": "cus_vectors01",
			},
		},
		{
			why:   "a failed payment, which must not by itself take anybody's plan away",
			event: "invoice.payment_failed",
			overrides: map[string]any{
				"id": "in_vectors02", "customer": "cus_vectors01",
			},
		},
		{
			why:   "the completed checkout, which carries the identifier an application put on the session",
			event: "checkout.session.completed",
			overrides: map[string]any{
				"id": "cs_vectors01", "customer": "cus_vectors01",
				"subscription": "sub_vectors01", "client_reference_id": "org-vectors",
			},
		},
	}

	out := vectorFile{
		Note: "Generated by engine/internal/webhook/vectors_test.go. These are real signed " +
			"events from the engine's webhook simulator. An application that verifies " +
			"signatures has to accept them, and the control plane proves it does in " +
			"web/apps/api/test/billing.test.ts. Regenerate with " +
			"'go test ./internal/webhook -update-vectors'.",
	}
	for _, c := range cases {
		event, err := webhook.Build("stripe", c.event, secret, c.overrides, signedAt)
		if err != nil {
			t.Fatal(err)
		}
		out.Events = append(out.Events, vectorEvent{
			Why:      c.why,
			Provider: event.Provider,
			Type:     event.Type,
			Secret:   secret,
			SignedAt: signedAt.Unix(),
			Body:     string(event.Body),
			Headers:  event.Headers,
		})
	}
	return out
}

func TestWebhookVectorsMatchTheCheckedInFile(t *testing.T) {
	want := buildWebhookVectors(t)
	encoded, err := json.MarshalIndent(want, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	encoded = append(encoded, '\n')

	path := filepath.Join("..", "..", "..", "schemas", "webhook-vectors.json")
	if *updateVectors {
		if err := os.WriteFile(path, encoded, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s", path)
		return
	}

	have, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("%v\n\nRegenerate with: go test ./internal/webhook -update-vectors", err)
	}
	if !bytes.Equal(bytes.TrimSpace(have), bytes.TrimSpace(encoded)) {
		t.Errorf("schemas/webhook-vectors.json is out of date with the signer.\n" +
			"The control plane proves its own verifier accepts these signatures, so a\n" +
			"stale file means the two are no longer being compared.\n\n" +
			"Regenerate with: go test ./internal/webhook -update-vectors")
	}
}

// A corpus that verified nothing would pass whatever the signer did.
func TestWebhookVectorsVerifyAgainstTheSigner(t *testing.T) {
	vectors := buildWebhookVectors(t)
	if len(vectors.Events) < 5 {
		t.Fatalf("only %d events in the corpus", len(vectors.Events))
	}
	for _, e := range vectors.Events {
		if !webhook.Verify(e.Provider, []byte(e.Body), e.Headers, e.Secret, signedAt) {
			t.Errorf("%s does not verify against the signer that produced it", e.Type)
		}
		// A negative control, so the loop above cannot pass vacuously.
		if webhook.Verify(e.Provider, append([]byte(e.Body), ' '), e.Headers, e.Secret, signedAt) {
			t.Errorf("%s verifies with a body that was changed", e.Type)
		}
	}
}
