// The parity test.
//
// Phase 8.6's exit criterion is that the control plane's explain matches the
// engine's for a corpus of requests. The corpus is not written here: it is
// generated by the Go implementation, checked in, and read by both.
//
// Every field is compared, including the exact wording of the reason, because
// the reason is what a person reads when a decision surprises them. Two
// engines that agree on the mode and disagree on why are two engines that will
// eventually disagree on the mode.

import { describe, it } from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { PolicyEngine, ALL_MODES, requestString, type Egress, type Mode } from '../src/index.ts'

const here = path.dirname(fileURLToPath(import.meta.url))
const vectorPath = path.join(here, '..', '..', '..', '..', 'schemas', 'policy-vectors.json')

interface VectorFile {
  note: string
  policies: VectorPolicy[]
}
interface VectorPolicy {
  name: string
  egress: Egress
  requests: VectorRequest[]
}
interface VectorRequest {
  request: { host: string; port?: number; method?: string; path?: string; tls?: boolean; string: string }
  decision: {
    mode: Mode
    rule_host?: string
    rate_limit?: string
    credential?: string
    fixtures?: string
    webhook_path?: string
    matched: boolean
    allowed: boolean
    reason: string
  }
  chain: { host: string; index: number; specificity: number; why: string }[]
  inspects_host: boolean
}

const vectors: VectorFile = JSON.parse(await readFile(vectorPath, 'utf8'))

describe('the policy engine reproduces the engine’s decisions', () => {
  it('reads a corpus that is not empty, so a missing file fails loudly', () => {
    assert.ok(vectors.policies.length >= 8, `only ${vectors.policies.length} policies in the corpus`)
    const requests = vectors.policies.reduce((n, p) => n + p.requests.length, 0)
    assert.ok(requests >= 30, `only ${requests} requests in the corpus`)
  })

  it('covers every mode, so none is left unimplemented here without failing', () => {
    const seen = new Set(vectors.policies.flatMap((p) => p.requests.map((r) => r.decision.mode)))
    for (const mode of ALL_MODES) {
      assert.ok(seen.has(mode), `the corpus never produces ${mode}`)
    }
  })

  for (const policy of vectors.policies) {
    describe(policy.name, () => {
      const engine = new PolicyEngine(policy.egress)

      for (const vector of policy.requests) {
        const req = {
          host: vector.request.host,
          port: vector.request.port,
          method: vector.request.method,
          path: vector.request.path,
          tls: vector.request.tls,
        }

        it(vector.request.string, () => {
          assert.equal(requestString(req), vector.request.string, 'the request renders differently')

          const { decision, chain } = engine.explain(req)

          assert.equal(decision.mode, vector.decision.mode, 'the mode differs')
          assert.equal(decision.ruleHost, vector.decision.rule_host ?? '', 'a different rule decided')
          assert.equal(decision.matched, vector.decision.matched)
          assert.equal(decision.allowed, vector.decision.allowed)
          assert.equal(decision.rateLimit, vector.decision.rate_limit ?? '')
          assert.equal(decision.credential, vector.decision.credential ?? '')
          assert.equal(decision.fixtures, vector.decision.fixtures ?? '')
          assert.equal(decision.webhookPath, vector.decision.webhook_path ?? '')
          assert.equal(decision.reason, vector.decision.reason, 'the reason reads differently')

          assert.deepEqual(
            chain.map((m) => ({
              host: m.rule.host, index: m.index, specificity: m.specificity, why: m.why,
            })),
            vector.chain,
            'the chain of matching rules differs, so the two would rank rules differently',
          )

          assert.equal(
            engine.inspectsHost(req.host, req.port ?? 0),
            vector.inspects_host,
            'the two disagree about whether this host needs TLS termination',
          )
        })
      }
    })
  }
})

describe('compilation refuses what the engine refuses', () => {
  const refused: [string, string][] = [
    ['', 'the host is empty'],
    ['*.', 'a wildcard needs a domain after it'],
    ['api.*.com', 'a wildcard is only allowed at the start'],
    ['*.exa*mple.com', 'a wildcard is only allowed at the start'],
    ['host:0', 'the port is not valid'],
    ['host:70000', 'the port is not valid'],
  ]
  for (const [host, fragment] of refused) {
    it(`refuses ${JSON.stringify(host)}`, () => {
      assert.throws(
        () => new PolicyEngine({ rules: [{ host, mode: 'allow' }] }),
        new RegExp(fragment.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')),
        // A rule that fails to compile and is skipped produces an engine that
        // enforces less than the manifest says while looking like it works.
        'a rule that cannot be compiled must be refused, never skipped',
      )
    })
  }
})

describe('address parsing does not widen a rule', () => {
  it('does not treat a name made of digits as an address', () => {
    const engine = new PolicyEngine({ rules: [{ host: '10.0.0.5', mode: 'allow' }] })
    assert.equal(engine.evaluate({ host: '10.0.0.5' }).mode, 'allow')
    assert.equal(engine.evaluate({ host: '10.0.0.55' }).mode, 'block')
    assert.equal(engine.evaluate({ host: '10.0.0.5.example.com' }).mode, 'block')
  })

  it('does not reinterpret leading zeros', () => {
    // 010.0.0.5 is 8.0.0.5 to an octal parser and 10.0.0.5 to a decimal one.
    // A rule that means different things to different readers is unreviewable,
    // so it is not an address at all.
    const engine = new PolicyEngine({ rules: [{ host: '10.0.0.5', mode: 'allow' }] })
    assert.equal(engine.evaluate({ host: '010.0.0.5' }).mode, 'block')
  })
})
