// Code generated by tools/lintgen. DO NOT EDIT.
//
// Source: engine/internal/insights/lintcatalog.yaml

package insights

// FindingID is the stable identifier for a lint finding.
//
// It is assigned once and never reused, including after the rule that earned
// it is deleted. Everything else about a finding is free to move: the rule
// name, the title, the detail and the fix are all prose and are improved
// whenever a clearer wording exists. Match on this.
type FindingID string

// findingIDs maps a rule to its identifier. A rule with no entry here has no
// identifier, which tools/lintcheck fails the build over.
var findingIDs = map[Rule]FindingID{
	"no_lock_timeout":                "LINT-001",
	"not_null_without_default":       "LINT-002",
	"set_not_null_existing_column":   "LINT-003",
	"alter_column_type":              "LINT-004",
	"index_not_concurrent":           "LINT-005",
	"drop_index_not_concurrent":      "LINT-006",
	"reindex_not_concurrent":         "LINT-007",
	"foreign_key_not_valid":          "LINT-008",
	"check_constraint_not_valid":     "LINT-009",
	"unique_constraint_builds_index": "LINT-010",
	"backfill_in_ddl_transaction":    "LINT-011",
	"rename_column_in_use":           "LINT-012",
	"drop_column_in_view":            "LINT-013",
	"vacuum_full":                    "LINT-014",
	"cluster":                        "LINT-015",
	"drop_table":                     "LINT-016",
	"truncate":                       "LINT-017",
}

// findingTitles is the one line summary of each rule, used as a heading in the
// report. The rationale and the fix live on the finding itself, because they
// depend on the table it found.
var findingTitles = map[Rule]string{
	"no_lock_timeout":                "no lock_timeout, so a lock wait becomes an outage",
	"not_null_without_default":       "NOT NULL column added with no default",
	"set_not_null_existing_column":   "NOT NULL set on a column that already exists",
	"alter_column_type":              "column type change that rewrites the table",
	"index_not_concurrent":           "index built without CONCURRENTLY",
	"drop_index_not_concurrent":      "index dropped without CONCURRENTLY",
	"reindex_not_concurrent":         "index rebuilt without CONCURRENTLY",
	"foreign_key_not_valid":          "foreign key added without NOT VALID",
	"check_constraint_not_valid":     "CHECK constraint added without NOT VALID",
	"unique_constraint_builds_index": "unique constraint that builds its index in place",
	"backfill_in_ddl_transaction":    "rows changed in the same transaction as the schema",
	"rename_column_in_use":           "column renamed while something still reads it",
	"drop_column_in_view":            "column dropped while a view still selects it",
	"vacuum_full":                    "VACUUM FULL, which rewrites the table offline",
	"cluster":                        "CLUSTER, which rewrites the table offline",
	"drop_table":                     "table dropped",
	"truncate":                       "table truncated",
}

// assignedFindingIDs is every identifier ever handed out, retired ones
// included, so that nothing can hand the same number out twice.
var assignedFindingIDs = []FindingID{
	"LINT-001",
	"LINT-002",
	"LINT-003",
	"LINT-004",
	"LINT-005",
	"LINT-006",
	"LINT-007",
	"LINT-008",
	"LINT-009",
	"LINT-010",
	"LINT-011",
	"LINT-012",
	"LINT-013",
	"LINT-014",
	"LINT-015",
	"LINT-016",
	"LINT-017",
}

// ID is the finding's stable identifier, or the empty string for a rule the
// catalogue does not know. Nothing reaches a user in that state: the build
// fails first.
func (r Rule) ID() FindingID { return findingIDs[r] }

// Title is the rule's one line summary.
func (r Rule) Title() string {
	if t, ok := findingTitles[r]; ok {
		return t
	}
	return string(r)
}

// AssignedFindingIDs returns every identifier the catalogue has ever assigned,
// in order.
func AssignedFindingIDs() []FindingID {
	return append([]FindingID(nil), assignedFindingIDs...)
}
